- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
Because
- we'd like to track issues and PRs in the [VDP](https://github.com/orgs/instill-ai/projects/5) project.
This commit
- add Github Actions to add issues and PRs to the VDP project according to [automating the project (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/managing-the-visibility-of-your-projects)
> ci: add issue and PR to Visual Data Preparation Project

- go.mod
- pkg/service/pipeline.go
Because
- The validation of the model should also be checked during updating the pipeline
- Should have a definition of the status for mode
This commit
- fix: add validation when update pipeline and fix bug
> fix: add validation when update pipeline and fix bug

- internal/definition/recipe.go
- internal/temporal/temporal.go
Because
- we align the new term in the type of recipe if the trigger is from HTTP/gRPC
This commit
- use direct instead of http for DS/DD in recipe
> fix: use direct instead of http for DS/DD in recipe

- pkg/repository/pipeline.go
- pkg/service/pipeline.go
Because
- all structs in pkg folder should be public
This commit
- expose all structs inside pkg folder
> fix: expose all structs inside pkg folder

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
- .github/workflows/coverage.yml
- pkg/repository/pipeline.go
Because
- we would like to regularly check test coverage of the codebase
This commit
- set up codecov action
- make GitHub Actions workflow name consistent
> ci: add codecov action

- .github/workflows/coverage.yml
- .gitignore
- README.md
- go.mod
- go.sum
- internal/temporal/temporal.go
Because
- we now have module `instill-ai/x` to share common package
This commit
- adopt `instill-ai/x/zapadapter` pacakge
- update `README.md`
- update `.gitignore`
- update codecov job
> chore: use instill-ai/x module for zapadapter

- .github/.codecov.yml
- cmd/main.go
- go.mod
- go.sum
- rpc/pipeline.go
Because
- response output standard follows snake_case to disambiguate REST and gRPC naming convention
This commit
- adopt protobuf@v0.1.5-alpha
- make codecov.yml unblock mode
- configure grpc-gateway to use snake_case
> fix: fix response in snake case

- .gitignore
- configs/config.yaml
- go.mod
- go.sum
- integration-test/rest.js
- internal/db/db.go
- internal/db/migration/000001_init.down.sql
- internal/db/migration/000001_init.up.sql
- internal/db/migration/000002_create_column_creator_id.down.sql
- internal/db/migration/000002_create_column_creator_id.up.sql
- internal/db/migration/000003_change_enabled_column_name.down.sql
- internal/db/migration/000003_change_enabled_column_name.up.sql
- internal/db/migration/000004_human_readable_name.down.sql
- internal/db/migration/000004_human_readable_name.up.sql
- internal/db/migration/000005_rename_pipeline_table_to_singular.down.sql
- internal/db/migration/000005_rename_pipeline_table_to_singular.up.sql
- internal/db/migration/000006_add_pipeline_status_column.down.sql
- internal/db/migration/000006_add_pipeline_status_column.up.sql
- pkg/datamodel/datamodel.go
- pkg/datamodel/recipe.go
- pkg/handler/handler.go
- pkg/handler/marshal.go
- pkg/repository/repository.go
- pkg/service/mock_model_grpc_test.go
- pkg/service/mock_repository_test.go
- pkg/service/service.go
Because
- pipeline requires various statuses to reflect its situation
This commit
- bridge enum type defined in the db and protobuf
- close #43 
- close #44
> chore: add pipeline status

- pkg/handler/fieldannotation.go
- pkg/handler/handler.go
Because
- protobuf message change bytes to content
- error when trigger a pipeline with grpc stream method
This commit
- update required fields
- fix read file length when trigger a pipeline
> chore: update protobuf message

- cmd/main/main.go
- go.mod
- go.sum
- pkg/usage/usage.go
Because
- upgrade usage collection
This commit
- move usage-related code into the usage package
- trigger the reporter before shutting down the server
> refactor: update usage reporter

- pkg/service/service.go
Because
- Trigger model timeout 5 seconds is not enough for making model inference
- Goroutines use sync.WaitGroup which does not decrease the counter due to exception errors
This commit
- Increase timeout to 30 seconds
- defer wg.Done() and end function when have any error
- close #79 
- close #77
> fix: pipeline trigger model hangout

- config/config.go
- config/config.yaml
- internal/constant/constant.go
- pkg/handler/handlercustom.go
Because
- max image file size should be configurable
This commit
- add `maximagesize` in server config
> chore: add config for max image file size

- .github/workflows/add-issue-to-prj.yml
- .github/workflows/add-pr-to-prj.yml
- README.md
- pkg/service/convert.go
Because
- instead of Visual Data Preparation, VDP is Versatile Data Pipeline now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline
> chore: update Visual Data Preparation to Versatile Data Pipeline

- cmd/main/main.go
- internal/external/external.go
- pkg/handler/handlercustom.go
- pkg/usage/usage.go
Because
- backend service should not be terminated because of connection to other services
This commit
- replace fatal logs with error logs
> fix: replace fatal logs with error logs

- .github/workflows/images.yml
- .github/workflows/integration-test-latest.yml
- .github/workflows/integration-test-rc.yml
- .github/workflows/pr-rc-check.yml
- .github/workflows/releases.yml
Because
- we are introducing the rc branch to make the ci/cd flow more robust 
This commit
- add corresponding GitHub actions
> ci: add rc workflows

- integration-test/const.js
- integration-test/grpc-pipeline-public-with-jwt.js
- integration-test/grpc-pipeline-public.js
- integration-test/grpc.js
- integration-test/rest-pipeline-public-with-jwt.js
- integration-test/rest-pipeline-public.js
- integration-test/rest.js
- pkg/middleware/misc.go
Because
- we want to test whether `jwt-sub` is supported by pipeline backend
This commit
- add integration tests for requests with `jwt-sub` header, these tests only run in  direct microservice mode
> test: update integration tests for requests with `jwt-sub` header

- pkg/constant/constant.go
- pkg/service/service_test.go
Because
- we use a more representative user ID
This commit
- update the default user id
> refactor: update default user id

- pkg/middleware/misc.go
Because
- we want to pass headers "request-id" to the backend
This commit
- update custom header
> refactor: update custom matcher

- go.mod
- go.sum
- integration-test/grpc-pipeline-private.js
- integration-test/grpc-pipeline-public.js
- integration-test/helper.js
- integration-test/proto/vdp/connector/v1alpha/connector.proto
- integration-test/proto/vdp/connector/v1alpha/connector_public_service.proto
- integration-test/proto/vdp/model/v1alpha/model.proto
- integration-test/proto/vdp/model/v1alpha/model_public_service.proto
- integration-test/rest-pipeline-private.js
- integration-test/rest-pipeline-public.js
- pkg/service/mock_connector_grpc_test.go
- pkg/service/mock_model_grpc_test.go
- pkg/service/service.go
- pkg/service/utils.go
Because
- The user ID can be changed now (in Instill Cloud), so using the owner ID is not reliable
This commit
- refactor owner of a pipeline to use the UUID, not the ID
- update protogen-go dependency
> chore: change owner from using id to uuid

- integration-test/grpc-pipeline-public-with-jwt.js
- integration-test/rest-pipeline-public-with-jwt.js
- internal/resource/resource.go
- pkg/handler/handlercustom.go
Because
- currently, if a user does not exist in mgmt-backend, returns 500 status error
This commit
- return 404 when a user does not exist
- return 401 when both `jwt-sub` and `owner-id` does not exist in the header 
- update tests
> chore: return 404 for non-exist user and 401 for non-existent headers

- cmd/main/main.go
- pkg/handler/handlercustom.go
- pkg/middleware/middleware.go
Because
- We create new client instance every time for `/v1alpha/pipelines/{id}/trigger-multipart` endpoint
This commit
- share the client instance with main service
> chore: remove redundant grpc and repository client instance

- internal/resource/resource.go
- pkg/constant/constant.go
- pkg/handler/handlercustom.go
- pkg/handler/publicHandler.go
- pkg/service/service.go
Because
- Pipeline will get `access_token` from headers. We should use this to find out the owner of this pipeline.
This commit
- Query `access_token` from redis to get owner permalink
> chore: check access_token in redis for trigger endpoint

- .github/workflows/integration-test.yml
- Makefile
- integration-test/const.js
- integration-test/grpc.js
- integration-test/rest.js
Because
- Need to simplify the integration test mode
This commit
- Add `API_GATEWAY_HOST`, `API_GATEWAY_PORT` and `API_GATEWAY_PROTOCOL` var. to simplify the integration test setting
> chore: refactor integration test mode

- integration-test/grpc-pipeline-public.js
- integration-test/grpc.js
- integration-test/rest-pipeline-public.js
- integration-test/rest.js
Because
- the integration tests didn't detect connector/model private port problem
This commit
- add integration tests for watch endpoint
> chore: add integration test for watch endpoint

- integration-test/grpc.js
- integration-test/rest.js
- pkg/service/mode.go
- pkg/service/service_test.go
Because
- multiple models and destinations are not supported in console yet
This commit
- add limitation for the number of model and destination
> chore: add temporary limitation for number of model and destination

- pkg/service/mode.go
Because
- for sync pipeline, the real-time response is the main point, so we add limitation for only allow one model here
This commit
- add constraint that sync pipeline can only have one model
> chore: add constraint that sync pipeline can only have one model

- integration-test/grpc.js
- integration-test/rest.js
Because
- the connector-definition in connector-backend have been updated
This commit
- update the integration-test to adopt this change
> chore: update integration test to support new connector definition

- integration-test/grpc-pipeline-private.js
- integration-test/grpc-pipeline-public-with-jwt.js
- integration-test/grpc-pipeline-public.js
- integration-test/grpc-trigger-async.js
- integration-test/grpc-trigger-sync.js
- integration-test/rest-pipeline-private.js
- integration-test/rest-pipeline-public-with-jwt.js
- integration-test/rest-pipeline-public.js
- integration-test/rest-trigger-async.js
- integration-test/rest-trigger-sync.js
- pkg/handler/fieldannotation.go
- pkg/handler/publicHandler.go
- pkg/service/service.go
Because
- The setting of pipeline may be complex, so we must let user has the ability to save the unfinished pipeline
This commit
- When creating pipeline, the desired state will be inactive
- If the pipeline desired state is active, then you can not update the pipeline
> chore: allow unfinished pipeline

- integration-test/grpc-pipeline-private.js
- integration-test/grpc-pipeline-public-with-jwt.js
- integration-test/grpc-pipeline-public.js
- integration-test/grpc-trigger-async.js
- integration-test/grpc-trigger-sync.js
- integration-test/rest-pipeline-private.js
- integration-test/rest-pipeline-public-with-jwt.js
- integration-test/rest-pipeline-public.js
- integration-test/rest-trigger-async.js
- integration-test/rest-trigger-sync.js
- pkg/handler/fieldannotation.go
Because
- the pipeline can not know the mode because we allow unfinished pipeline
This commit
- let pipeline mode be unspecified when created
> chore: let pipeline mode be unspecified when created

- pkg/external/external.go
- pkg/service/influx.go
Because
- cause fatal error if influxdb is not present
This commit
- add temporary check for influxdb, influxdb will be always present soon as `base` adopt new envs
> chore: add temporary check if influxdb is present

- integration-test/grpc-pipeline-public.js
- integration-test/rest-pipeline-public.js
- pkg/handler/fieldannotation.go
- pkg/repository/repository.go
- pkg/service/mode.go
- pkg/service/service.go
- pkg/worker/workflow.go
Because
- we may have large size data in temporal output, we must put them in another storage
This commit
- use redis as data blob for both temporal input/output
- refactor check recipe and pipeline activation logic
> chore: use redis as data blob for both temporal input/output

- go.mod
- go.sum
- pkg/handler/publicHandler.go
- pkg/service/service.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- drop pipeline mode
- add connector `execute` metric in `connector-backend`
This commit
- rename pipeline mode to trigger mode
- add `pipelineTriggerId` in payload metadata
> chore(metric): update pipeline metric

- integration-test/const.js
- integration-test/grpc-trigger-async.js
- integration-test/grpc.js
- integration-test/rest-trigger-async.js
- integration-test/rest.js
Because
- For the pipeline triggerAsync, we'll return the operation id. We should use the operation id to get the trigger result.
This commit
- Add simple testcases for triggerAsync and getOperation
> chore: add simple testcases for triggerAsync and getOperation

- go.mod
- go.sum
- pkg/usage/usage.go
Because
- avoid complex query for usage metrics
This commit
- adopt new usage-client to add `owner_uid` in session
> chore(usage): adopt new usage-client to include owner_uid in session

- cmd/migration/000003_migrate.go
- go.mod
- go.sum
- integration-test/const.js
- integration-test/grpc-pipeline-public.js
- integration-test/grpc.js
- integration-test/proto/vdp/connector/v1alpha/connector.proto
- integration-test/proto/vdp/connector/v1alpha/connector_definition.proto
- integration-test/proto/vdp/connector/v1alpha/connector_private_service.proto
- integration-test/proto/vdp/connector/v1alpha/connector_public_service.proto
- integration-test/proto/vdp/pipeline/v1alpha/common.proto
- integration-test/proto/vdp/pipeline/v1alpha/operator_definition.proto
- integration-test/proto/vdp/pipeline/v1alpha/pipeline.proto
- integration-test/rest.js
- pkg/datamodel/datamodel.go
- pkg/handler/convert.go
- pkg/handler/privateHandler.go
- pkg/handler/publicHandler.go
- pkg/operator/operator.go
- pkg/service/convert.go
- pkg/service/mock_connector_private_grpc_test.go
- pkg/service/mock_connector_public_grpc_test.go
- pkg/service/service.go
- pkg/service/validator.go
- pkg/worker/workflow.go
Because
- In proto, `Connector` has been renamed to `ConnectorResource`
This commit
- adopt `connector-resources/` endpoints
> chore: adopt `connector-resources` endpoints

- integration-test/const.js
- pkg/operator/end/config/definitions.json
- pkg/operator/end/config/seed/component.json
- pkg/operator/operator.go
- pkg/operator/start/config/definitions.json
- pkg/operator/start/config/seed/component.json
- pkg/service/service.go
- pkg/worker/workflow.go
Because
- we will generate OpenAPI-schema for each pipeline, thus, we need `title` and `description` fields for start and end operators
This commit
- add `title` and `description` fields for start and end operator
> chore: add `title` and `description` fields for start and end operator

- go.mod
- go.sum
- pkg/handler/privateHandler.go
- pkg/handler/publicHandler.go
- pkg/handler/utils.go
- pkg/service/convert.go
- pkg/service/service.go
Because
- we need to have a intermediate view mode between `VIEW_BASIC` and `VIEW_FULL`, which return recipe without embedding its related connector resources or definitions.
- we should allow creating pipeline without connector-resource created
This commit
- add view mode `VIEW_RECIPE`
- allow creating pipeline without connector-resource created
> chore: add VIEW_RECIPE view mode

- go.mod
- go.sum
- pkg/service/convert.go
- pkg/service/openapi.go
- pkg/service/service.go
Because
- We can derive the input/output of pipeline trigger endpoints from pipeline recipe. Thus, we can generate the OpenAPI schema and use this schema to generate code snippet.
This commit
- Implement OpenAPI schema generator
> chore: generate OpenAPI schema for each pipeline automatically

- cmd/main/main.go
- pkg/handler/handle.go
Because
- the multipart handler didn't use the right path
This commit
- fix namespace problem for multipart handler
> chore: fix namespace problem for multipart handler

- go.mod
- go.sum
- pkg/handler/publicHandler.go
- pkg/repository/repository.go
- pkg/service/service.go
Because
- we need a special version tag `latest` point to the latest version (ordered by semantic version)
This commit
- add `latest` tag for pipeline releases
> chore: add `latest` tag for pipeline releases

- go.mod
- go.sum
- pkg/service/convert.go
Because
- we return `connector_definition` twice in recipe when using `view=VIEW_FULL`
This commit
- remove duplicated `connector_definition` in recipe
> chore: remove duplicated connector_definition in recipe

- pkg/service/service.go
- pkg/utils/dag.go
Because
- the `api_token` checker was missing
This commit
- check `api_token` in header
> chore: check `api_token` in header

- pkg/constant/constant.go
- pkg/service/service.go
Because
- we want to centralize all `api_token` check logic in api-gateway
This commit
- remove `api_token` check logic
> chore: remove api_token check logic

- Makefile
- integration-test/const.js
- pkg/operator/end/config/definitions.json
- pkg/operator/end/config/seed/component.json
- pkg/operator/start/config/definitions.json
- pkg/operator/start/config/seed/component.json
- pkg/service/openapi.go
- pkg/service/service.go
- pkg/worker/workflow.go
Because
- the `body` layer in start/end operator is redudent. 
This commit
- remove `body` in start/end operator to simplify the recipe
> chore: remove `body` in start/end operator to simplify recipe

- pkg/handler/publicHandler.go
- pkg/service/service.go
- pkg/usage/usage.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- support pipeline release feature
This commit
- add pipeline release info in usage/metric data
> chore(usage,metric): add pipeline release info in usage/metric data

- pkg/handler/publicHandler.go
Because
- fix pipeline release nil uuid value
This commit
- fix pipeline release nil uuid value
> chore(metric): fix pipeline release nil uuid value

- cmd/main/main.go
- pkg/constant/constant.go
- pkg/external/external.go
Because
- the default grpc message size limit is only 4MB, which is not enough
This commit
- increase grpc message size limit to 32MB
> chore: increase grpc message size limit

- pkg/service/service.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- let the reference and template can reference value from global data: `pipeline`, `owner`
This commit
- support global data reference(pipeline, owner)
- temporary solution: inject global data for numbers connector
> chore: support global data reference(pipeline, owner)

- pkg/service/convert.go
- pkg/service/service.go
Because
- the pipeline-backend didn't correctly call connector-backend
This commit
- fix connector `jwt-sub` propagation bug
> chore: fix connector jwt-sub propagation bug

- pkg/service/convert.go
Because
- the OpenAPI generator has bug
This commit
- fix OpenAPI generator bug
> chore: fix OpenAPI generator bug

- pkg/service/openapi.go
Because
- the OpenAPI generation might cause pipeline response error
This commit
- fix OpenAPI generation bug
> chore: fix OpenAPI generation bug

- pkg/service/openapi.go
Because
- the schema generator bug might accidentally include the full schema of component input or output
This commit
- fix OpenAPI schema generator bug
> chore: fix OpenAPI schema generator bug

- go.mod
- go.sum
- pkg/handler/privateHandler.go
- pkg/handler/publicHandler.go
- pkg/usage/usage.go
Because
- the grpc-gateway will convert `int64` to `string`
This commit
- use `int32` for `page_size` and `total_size` to avoid this problem
> fix(proto,handler): use `int32` in proto pkg to prevent the `total_size` converted to `string`

- pkg/service/validator.go
Because
- the UX for checking connector resource state when releasing is not friendly
This commit
- remove connector resource state check
> chore(service): remove connector resource state check

- pkg/service/convert.go
Because
- the pipeline_release endpoints has bug when `view=VIEW_FULL`
This commit
- fix pipeline_release recipe conversion bug
> fix(service): fix pipeline_release recipe conversion bug

- pkg/service/service.go
Because
- the pipeline_release should be deleted when pipeline is deleted, or it will be dangling 
This commit
- delete pipeline_release when pipeline is deleted
> fix(service): delete pipeline_release when pipeline is deleted

- cmd/main/main.go
- pkg/constant/constant.go
- pkg/service/service.go
Because
- the `user_id` injection in backend is unsafe
- we are going to change the default_user_id to `admin`
This commit
- remove `user_id` injection
- change the default_user_id to `admin`
> chore(service): remove unsafe user_id injection and update default_user_id

- config/config.yaml
- go.mod
- go.sum
- pkg/constant/constant.go
- pkg/datamodel/datamodel.go
- pkg/db/migration/000005_init.up.sql
- pkg/middleware/misc.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/service.go
Because
- we need to support public sharing for pipeline and sharing by link
This commit
- support permission setting
- support sharing pipeline public
- support sharing pipeline by code(link)
> feat(permission): support permission setting, sharing public, sharing by code(link)

- pkg/constant/constant.go
- pkg/middleware/misc.go
Because
- the original header `Instill-Code` has no clear meaning
This commit
- rename it to `Instill-Share-Code`
> chore(permission): rename the share-code permission header

- go.mod
- go.sum
- pkg/service/convert.go
- pkg/service/service.go
Because
- we need to show the `pipeline_release` `alias` name in response
This commit
- add `alias` field for `pipeline_release`
> chore(service): add `alias` field for `pipeline_release`

- pkg/handler/publicHandler.go
Because
- the recipe should preserve its original content when not patching it
This commit
- fix PATCH pipeline mask bug
> fix(handler): fix PATCH pipeline mask bug

- pkg/service/openapi.go
- pkg/service/service.go
Because
- the state of pipeline_release was not correctly set
This commit
- fix pipeline_release state bug
> fix(service): fix pipeline_release state bug

- Dockerfile
- Dockerfile.dev
Because
- need to add dependencies for text extraction operator 
This commit
- use alpine base image
- add text extraction operator dependencies in Dockerfile
> chore: add text extraction dependencies in Dockerfile

- cmd/main/main.go
Because
- Currently backends in Instill Base Instill VDP and Instill Model will emit a huge amount of logs with level Info, which can overwhelm stdout
This commit
- Refactor grpc logger `verbosity` and bypass successful private function calls
> refactor(logging): reduce unnecessary log emission

- cmd/main/main.go
- cmd/migration/000002_migrate.go
- cmd/migration/000003_migrate.go
- cmd/migration/000006_migrate.go
- cmd/worker/main.go
- pkg/db/db.go
Because
- migration processes were using a shared db connection causing the very first migration process early closing the db connection resulting the subsequent migration processes failed to connect the db.
- this issue wasn't obvious in a `docker compose up` scenario because the restart policy `restart: on-failure` simply has the `pipeline-backend-migration` container re-launched several time until all migration processes are finished.
This commit
- make the migration processes using non-shared db connection
> fix(migration): fix db connection bug

- Dockerfile
- pkg/utils/utils.go
Because
- when we have `input` in start operator, the trigger will be error when set `instill-return-traces=true`
This commit
- fix trigger error when start operator has field `input`
- fix `unrtf` package install error
- close https://github.com/instill-ai/community/issues/474
> fix(pipeline): fix trigger error when start operator has field `input`

- go.mod
- go.sum
- integration-test/const.js
- pkg/handler/handle.go
- pkg/service/openapi.go
- pkg/service/service.go
- pkg/utils/utils.go
Because
- we'd like to refactor start operator so that it has a JSON-schema structure similar to other components.
- we should use json encoded string in form-data
This commit
- refactor start operator to use `instillAcceptFormats`
- update corresponding OpenAPI generator
> refactor(pipeline): update start operator flows

- go.mod
- go.sum
- internal/resource/resource.go
- pkg/handler/handle.go
- pkg/handler/privateHandler.go
- pkg/handler/publicHandler.go
- pkg/service/service.go
- pkg/service/state.go
- pkg/service/validator.go
- pkg/worker/workflow.go
Because
- We didn't handle the data validation well. We need to validate pipeline input and component input/output data and return proper error messages
This commit
- Improve the data validation and its error handling
> refactor(service): improve the data validation and its error handling

- pkg/handler/fieldannotation.go
- pkg/handler/publicHandler.go
- pkg/service/validator.go
- pkg/utils/dag.go
Because
- the error message formats of recipe validation are not consistent
This commit
- optimize recipe validation error message
- add pipeline recipe validation before triggering
> refactor(service): optimize recipe validation error message

- pkg/utils/utils.go
Because
- we don't need to return the trace data for op-end operator, since it is identical to the trigger response
This commit
- remove op-end traces data
> chore(service): remove op-end traces data

- pkg/service/service.go
- pkg/worker/workflow.go
Because
- the trigger function didn't get the correct component definitions
This commit
- fix trigger component error
> chore(service): fix trigger component error

- Dockerfile
- Dockerfile.dev
- go.mod
- go.sum
Because
- the Text operator `TASK_CONVERT_TO_TEXT` requires Tesseract OCR to be built with `-tags=ocr`
This commit
- add corresponding dependencies in the Docker image
- catch up with the operator package
> chore(dockerfile): add gosseract to enable docconv ocr build

- Dockerfile
Because
- `CGO_ENABLED=1` is required for gosseract to build
This commit
- add the env variable accordingly
> ci(dockerfile): fix build

- .github/workflows/images.yml
- Dockerfile
Because
- there is some problem when cross compiling with `CGO_ENABLED=1`
This commit
- use QEMU docker to cross compile arm64 image
> ci(image): use QEMU docker to cross compile arm64 image

- pkg/db/migration/000008_init.up.sql
Because
- the db migration didn't update "connector-resource" -> "connector" renaming
This commit
- fix db migration about the connectors renaming
> chore(migration): fix db migration about the connectors renaming

- go.mod
- go.sum
- pkg/handler/connector.go
- pkg/handler/pipeline.go
- pkg/service/service.go
- pkg/usage/usage.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- adopt org and acl data collection for usage and metric
This commit
- add `owner` and `user` data in each trigger/execute and support `org` type
> chore(usage,metric): adopt latest protobuf to add org data

- pkg/service/service.go
- pkg/utils/dag.go
- pkg/worker/workflow.go
Because
- we want to record component execution status so we can have a better flow control in the future
This commit
- implement component status
> feat(pipeline): implement component status

- cmd/worker/main.go
- pkg/service/service.go
- pkg/worker/worker.go
- pkg/worker/workflow.go
Because
- We want to use Temporal to serve all pipeline jobs for the robustness.
This commit
- use Temporal as worker queue for `trigger` endpoint
> refactor(service): use Temporal as worker queue for `trigger` endpoint

- go.sum
- pkg/middleware/interceptor.go
- pkg/service/errors.go
- pkg/service/service.go
Because
- we need to rate limit the pipeline trigger
This commit
- implement trigger rate-limit, if the value is not set in Redis, we'll ignore that.
> feat(service): implement trigger rate-limit

- cmd/main/main.go
- config/config.go
- config/config.yaml
- pkg/external/external.go
- pkg/service/service.go
Because
- we need to use public endpoints to get the user or org subscription
This commit
- use mgmtPublicClient to get subscription
> chore(serivce): use mgmtPublicClient to get subscription

- pkg/service/convert.go
Because
- the pipeline payload embed wrong releases
This commit
- fix returning wrong releases in pipeline payload
> chore(service): fix returning wrong releases in pipeline payload

- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/worker/workflow.go
Because
- we'll support internal network mode for instill-model connector
This commit
- setup user jwt-sub and model-backend url for instill-model connector
> chore(workflow): setup user jwt-sub and model-backend url for instill-model connector

- pkg/service/service.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- we need to cache private trigger count
This commit
- use Redis to cache private trigger count
> chore(workflow): use Redis to cache trigger count

- config/config.yaml
- go.mod
- go.sum
- pkg/acl/acl.go
- pkg/datamodel/datamodel.go
- pkg/db/migration/000010_init.up.sql
- pkg/service/convert.go
- pkg/service/service.go
- pkg/utils/dag.go
- pkg/worker/workflow.go
Because
- We are going to refactor `pipeline.permission` as the corresponding permission of the authenticated user. And the original pipeline permission setting will now be `pipeline.sharing`
This commit
- refactor `pipeline.permission` and `pipeline.sharing`
- return corresponding permissions of the authenticated user
> refactor(service): refactor `pipeline.permission` and `pipeline.sharing`

- pkg/worker/workflow.go
Because
- fix wrong organization namespace
This commit
- fix wrong organization namespace
> chore(metrics): fix wrong organization namespace

- pkg/service/service.go
Because
- we'll allow unlimited trigger quota in some pricing plan
This commit
- handle unlimited trigger quota
> chore: handle unlimited trigger quota

- go.mod
- go.sum
- pkg/service/openapi.go
Because
- pipeline can not generate correct output schema when it contains `semi-structured/object`
This commit
- fix pipeline can not generate correct output schema
> fix: fix pipeline can not generate correct output schema

- integration-test/connector/const.js
- integration-test/connector/grpc-data-connector-public-with-jwt.js
- integration-test/connector/grpc.js
- integration-test/connector/rest-data-connector-public-with-jwt.js
- integration-test/connector/rest.js
- integration-test/pipeline/const.js
- integration-test/pipeline/grpc-pipeline-public-with-jwt.js
- integration-test/pipeline/rest-pipeline-public-with-jwt.js
- pkg/constant/constant.go
- pkg/middleware/misc.go
- pkg/service/service.go
- pkg/utils/utils.go
- pkg/worker/workflow.go
Because
- we want to remove unnecessary request to improve the performance
- need to standardize the naming convention of our headers 
This commit
- remove unnecessary mgmt-backend request
- change header `jwt-sub` to `Instill-User-Uid`
> fix: remove unnecessary mgmt-backend request

- config/config.yaml
Because
- We only need retry for component execution, which is served by Temporal Activity. The Workflow retry is not needed since the recipe is the same, if it fail, it should fail forever.
This commit
- fix the wrong Temporal workflow retry setting
> fix: fix the wrong Temporal workflow retry setting

- cmd/init/main.go
- go.mod
- go.sum
- integration-test/connector/const.js
- integration-test/connector/grpc-data-connector-public-with-jwt.js
- integration-test/connector/grpc-data-connector-public.js
- integration-test/connector/rest-data-connector-public-with-jwt.js
- integration-test/connector/rest-data-connector-public.js
- integration-test/pipeline/const.js
- integration-test/pipeline/grpc.js
- integration-test/pipeline/rest.js
Because
- Airbyte connectors have been merged into one
This commit
- update test-cases for Airbyte connector
- remove `PreDownloadImage()`
> chore: update test-cases for Airbyte connector

- pkg/handler/connector.go
Because
- Originally, we used the `instill-` prefix to distinguish connectors owned by Instill AI from those owned by the user. Now, with separate namespaces for users, we no longer require this constraint.
This commit
- remove connector id prefix constraint
> chore: remove connector id prefix constraint

- go.mod
- go.sum
- integration-test/pipeline/const.js
- pkg/service/openapi.go
- pkg/utils/dag.go
- pkg/worker/workflow.go
Because
- Originally, we had two syntax options: `{}` and `{{}}` for reference and string literals (Liquid template). There were two main problems: 
1. Users were easily confused by these two, and Liquid template is actually not a must-have feature in component input.
2. We would encounter syntax conflicts when trying to input a JSON string.
This commit
- Uses `${}` as the reference syntax to avoid conflict with JSON string.
- Updates the condition syntax to use `${}` as well.
> feat(recipe): use `${}` as reference syntax

- go.mod
- go.sum
- pkg/service/convert.go
- pkg/service/service.go
- pkg/service/validator.go
- pkg/utils/dag.go
- pkg/worker/workflow.go
Because
Originally, our connector definitions are fixed. However, in some scenarios, the definition will be dynamic.
The component JSON schema can be influenced by connector configuration. For example, the Instill Model Connector can retrieve the model list and incorporate it into the component JSON schema as an enumeration.
The OpenAPI schema can be influenced by both connector and component configuration. For example, we can let user define the JSON schema of the output body in the RestAPI connector and utilize it to generate the OpenAPI schema of the RestAPI connector.
Therefore, we would like to make these connector definitions dynamically generated.
This commit
- support dynamic connector and operator definition
> feat: support dynamic connector and operator definition

- pkg/handler/pipeline.go
- pkg/repository/transpiler.go
Because
- We want to introduce a feature that allows users to search for pipelines by `id` using fuzzy search instead of exact matching.
This commit
- Supports the `q` filter for fuzzy searching on `id`.
> feat: support `q` filter for fuzzy search on `id`

- pkg/worker/workflow.go
Because
- We've changed the reference syntax.
This commit
- Fix wrong global reference for Numbers connector.
> fix: fix wrong global reference for Numbers connector

- pkg/utils/dag.go
- pkg/utils/utils.go
- pkg/worker/worker.go
- pkg/worker/workflow.go
Because
- Originally, the pipeline DAG executed the components sequentially. However, some of the components can be executed in parallel.
This commit
- Executes components in parallel.
> feat: execute component in parallel

- go.mod
- go.sum
- pkg/usage/usage.go
Because
- pipeline_id is more informative in the context of grafana dashboard
This commit
- add pipeline_id in PipelineUsageData
resolves INS-3467
> chore(usage): add pipeline id in usage data

- pkg/worker/workflow.go
Because
- https://github.com/instill-ai/connector/pull/113 introduced an [end-user error](https://github.com/instill-ai/connector/pull/113/files#diff-ccd0d26c1e8d29bcffb2741e853132db31305425679cdc929b82eb8af6c3824cR79) in a `CreateExecution` function, which isn't displayed correctly in console.
This commit
- Checks the response from `CreateExecution` and adds any potential end-user error as a Temporal error message.
> feat: add end-user errors on CreateExecution error

- go.mod
- go.sum
Because
- https://github.com/instill-ai/connector/pull/113 introduced a new connector, Archetype AI.
This commit
- go.mod is updated in order to reflect the addition of the connector in VDP.
> chore: update connector version

- go.mod
- go.sum
- pkg/handler/pipeline.go
- pkg/service/service.go
Because
- We'd want to let user filter namespace's pipelines by `visibility` 
This commit
- Support `visibility` param in list namespace pipelines endpoints
> feat: support `visibility` param in list namespace pipelines endpoints

- go.mod
- go.sum
- pkg/handler/pipeline.go
- pkg/service/service.go
Because
- We want to provide an API to let user clone the pipeline recipe.
This commit
- Add `CloneUserPipeline` and `CloneOrganizationPipeline` endpoints
> feat: add `CloneUserPipeline` and `CloneOrganizationPipeline` endpoints

- pkg/service/service.go
Because
- The pipeline restore API will return 500 error.
This commit
-  Fix can not restoring pipeline recipe from releases
> fix: fix can not restore pipeline recipe from releases

- integration-test/pipeline/const.js
- integration-test/pipeline/grpc.js
Because
- Some test-cases are flaky due to timeout.
This commit
- Increase timeout in test
> test: increase timeout

- pkg/service/openapi.go
- pkg/utils/dag.go
Because
- Initially, we used the `${[comp.xxx, comp.yyy]}` operation to construct an array. However, it was not very straightforward, and we want to keep the syntax as pure as possible, retaining only the variable index ability. Additionally, we plan to use the JSON operator for array construction in the future.
This commit
- Removes the `${[comp.xxx, comp.yyy]}` operation from the component reference syntax.
> feat: remove `${[ ]}` operator in component reference syntax

- go.mod
- go.sum
- pkg/handler/pipeline.go
- pkg/service/service.go
- pkg/utils/dag.go
Because
- In numerous use cases, our goal is to integrate diverse data types (e.g., numbers, JSON) into the string template.
This commit
- Enables string data to reference all stringifiable data types. JSON-marshallable data will be converted to a string, and binary data will be represented by a base64 string.
- Removes the "Liquid" engine, retaining only the pure reference approach.
- Fixes bug when using `semi-structured/json` input in start operator.
> feat: allow the string data to reference all data types that can be stringified

- pkg/service/service.go
Because
- We need to propagate the `Instill-` headers to other services.
This commit
- Refactors context header injection by adding a `injectAuthUserToContext()`
> refactor: refactor context header injection

- Dockerfile
Because
- we want to make the backend container self-healthcheck so the other dependencies can precisely know the container health status
This commit
- add `curl` for running `curl -f http://${PIPELINE_BACKEND_HOST}:${PIPELINE_BACKEND_PUBLICPORT}/v1beta/health/pipeline` in docker compose `healthcheck`
> ci(Dockerfile): add curl

- cmd/worker/main.go
- config/config.go
- config/config.yaml
Because
- make temporal namespace programmatically created to remove the `temporal-admin-tools` container at launch
This commit
- add initialisation temporal namespace logic in the worker `main.go`
- the implementation will skip the namespace creation if it already exists
> chore(worker): create temporal namespace at launch

- go.mod
- go.sum
- pkg/service/service.go
Because
- The request to the subscription endpoint is not up to date.
This commit
- Adopts the latest mgmt subscription endpoint and uses `mgmtPrivateServiceClient` to connect to mgmt.
- Removes `profile_data` in pipeline response.
> chore: adopt latest mgmt subscription endpoint

- cmd/worker/main.go
- go.mod
- go.sum
- pkg/service/openapi.go
- pkg/utils/dag.go
Because
- Originally, when performing object traversing, we only supported the child operator in `foo.bar` syntax. However, this approach failed when dealing with a key containing a space. To address this limitation, we needed to implement support for the child operator in `foo["bar"]` syntax. This change ensures that keys like `my var` can function correctly with `foo["my var"]`.
- Temporal worker might stuck into infinite retry loop if there is unexpected error.
This commit
- Supports references with the `foo["bar"]` syntax.
- Changes JSONPath library.
- Updates Temporal worker setting to avoid infinite retry.
Note
- The `openapi.go` is very messy, we'll refactor it soon.
> feat: support reference with `foo["bar"]` syntax

- integration-test/connector/const.js
- integration-test/connector/grpc-data-connector-definition.js
- integration-test/connector/grpc-data-connector-private.js
- integration-test/connector/grpc-data-connector-public-with-jwt.js
- integration-test/connector/grpc-data-connector-public.js
- integration-test/connector/grpc.js
- integration-test/connector/helper.js
- integration-test/connector/rest-data-connector-definition.js
- integration-test/connector/rest-data-connector-private.js
- integration-test/connector/rest-data-connector-public-with-jwt.js
- integration-test/connector/rest-data-connector-public.js
- integration-test/connector/rest.js
- integration-test/pipeline/const.js
- integration-test/pipeline/grpc-pipeline-private.js
- integration-test/pipeline/grpc-pipeline-public-with-jwt.js
- integration-test/pipeline/grpc-pipeline-public.js
- integration-test/pipeline/grpc-trigger-async.js
- integration-test/pipeline/grpc-trigger.js
- integration-test/pipeline/grpc.js
- integration-test/pipeline/helper.js
- integration-test/pipeline/rest-pipeline-private.js
- integration-test/pipeline/rest-pipeline-public-with-jwt.js
- integration-test/pipeline/rest-pipeline-public.js
- integration-test/pipeline/rest-trigger-async.js
- integration-test/pipeline/rest-trigger.js
- integration-test/pipeline/rest.js
- integration-test/proto/core/mgmt/v1beta/metric.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_public_service.proto
Because
- We will run pipeline integration tests together with other backend tests. The owner profile data might be changed by other backends. We need to use the real data from the database as the expected result instead of using the hardcoded one.
This commit
- Uses owner profile from mgmtdb as the expected result
> test: use owner profile from mgmtdb as expected result

- .github/workflows/integration-test.yml
Because
- We refactored the entire Instill project structure, the existing GA won't work.
This commit
- Adopts latest project structure
> ci: adopt latest project structure

- cmd/worker/main.go
- go.mod
- go.sum
- integration-test/pipeline/const.js
- integration-test/pipeline/grpc-pipeline-private.js
- integration-test/pipeline/grpc-pipeline-public.js
- integration-test/pipeline/rest-pipeline-private.js
- integration-test/pipeline/rest-pipeline-public.js
- integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
- pkg/datamodel/datamodel.go
- pkg/handler/pipeline.go
- pkg/service/convert.go
- pkg/service/openapi.go
- pkg/service/service.go
- pkg/utils/utils.go
- pkg/worker/dag.go
- pkg/worker/worker.go
- pkg/worker/workflow.go
Because:
- The original recipe message utilized `structpb` to encapsulate every configuration, creating an implicit structure that posed a challenge for users or developers to comprehend the data structure. Given the distinct structures associated with various components, it is essential to explicitly expose them to the user.
- A special iterator component for array data iteration is desired.
This commit:
- Revamped the recipe with new Protobuf messages: `StartComponent`, `EndComponent`, `OperatorComponent`, `ConnectorComponent`, and `IteratorComponent`.
- Implements iterator.
Note:
- This is a breaking change in the interface, requiring an update to the implementation on the client-side.
> feat: revamp recipe format and implement iterator

- cmd/init/main.go
- cmd/init/main_test.go
- integration-test/pipeline/rest-component-definition.js
- pkg/datamodel/datamodel.go
Because
- We want a way to feature / promote some components in the component page.
This commit
- Adds a map with the component ID -> component score, which will be used in the component definition table in DB to sort the filtered / paginated results.
- Because this is decoupled from the `definitions.json` file (reasoning [here](https://linear.app/instill-ai/issue/INS-3738/sort-component-lists-by-score#comment-9f1a1f51)), changes in these scores will trigger a database component definition update. The init logic that keeps the table up to date is refactored a little bit.
> feat: sort component list by score

- pkg/service/convert.go
Because
- The original implementation of `includeIteratorComponentDetail()` cannot handle incomplete or invalid component configurations.
This commit
- Refactors and allows incomplete or invalid component configurations in `includeIteratorComponentDetail()`.
> fix: allow incomplete configuration in includeIteratorComponentDetail().

- go.mod
- go.sum
- integration-test/pipeline/rest-component-definition.js
- pkg/datamodel/datamodel.go
- pkg/service/service.go
Because
- Component page showcases unimplemented components with the "Open for contribution" and "Coming soon" tags.
This commit
- Uses the new `release_stage` property introduced in https://github.com/instill-ai/protobufs/pull/283
> feat: support unimplemented release stages in component definitions

- integration-test/pipeline/rest-component-definition.js
- pkg/repository/repository.go
Because
- Some results were repeated across pages in the component definitions endpoint
This happens because the results were sorted by `feature_score` at the database level before paginating. The rest of the results (score 0) were unsorted, which causes an arbitrary order in each query.
This commit
- Sorts the results by UID before paginating
- Additionally, it sorts them by release stage (given the same score, we'll want to have the more stable components first).
> fix: duplicated values in component list

- cmd/worker/main.go
- go.mod
- pkg/worker/worker.go
- pkg/worker/workflow.go
Because
- We encountered bugs that Temporal will complain about, stating "potential deadlock detected." This is a Temporal workflow mechanism designed to detect problematic workflows. We cannot have blocking functions or code in the Temporal workflow for more than 1 second. We must move those time-consuming implementations into Temporal activities.
This commit
- Refactors pipeline activities. Adds new TriggerStart and TriggerEnd activities for pre and post-processing. Flattens the connector and operator activities into DAG activities.
Note:
- This is a quick fix for functionality. The codebases will be further refactored soon.
> refactor: refactor pipeline activities

- cmd/init/main.go
- cmd/main/main.go
- cmd/worker/main.go
- config/config.go
- go.mod
- go.sum
- internal/resource/resource.go
- pkg/acl/acl.go
- pkg/constant/constant.go
- pkg/db/db.go
- pkg/handler/connector.go
- pkg/handler/handler.go
- pkg/handler/pipeline.go
- pkg/handler/utils.go
- pkg/logger/otel/const.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/service.go
- pkg/usage/usage.go
- pkg/worker/worker.go
- pkg/worker/workflow.go
Because
- Since there will be replication lag in the database replica, we will encounter the "read-after-write inconsistency" problem when deploying Core in a multi-region cluster. In our use case, we can choose the "Pinning User to Primary Database" approach as our first step. This means that after the user mutates some data, there will be a small time frame during which this user will always read data from the primary database, regardless of their location. This way, we can ensure read-after-write consistency.
This commit
- Pins the user to read from the primary database for a certain time frame after mutating the data.
- Refactors code to retrieve `authUser` data from context directly.
> feat: pin the user to read from the primary database for a certain time frame after mutating the data

- cmd/init/main.go
- cmd/main/main.go
- config/config.go
- pkg/acl/acl.go
Because
- In the multi-region deployment, we will separate the read/write operations into different databases and OpenFGA engines.
This commit
- Adds connection settings for OpenFGA read replica.
- Separates read/write modes into different OpenFGA engines.
> feat: add connection to read replica OpenFGA

- cmd/init/main.go
- pkg/datamodel/datamodel.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/service.go
Because
- The performance is poor in a multi-region structure.
This commit
- Optimizes performance by reducing database round-trips and removing unnecessary queries.
> refactor: optimize performance

- Makefile
- go.mod
- go.sum
- pkg/service/convert.go
- pkg/service/service.go
- pkg/worker/workflow.go
Because
- The Instill Model connector can't work properly in internal mode since the pods in different region clusters can't connect to each other, we decided to use external IP and bypass the user authorization.
This commit
- Fixes the multi-region connection problem by bypassing the user authorization header.
> fix: fix multi-region connection problem for Instill Model connector

- cmd/init/main.go
- config/config.go
- pkg/service/convert.go
Because
- In Instill Cloud, the Instill Model connector will frequently send GET requests to /models endpoint, as it connects to Instill Model through an external network, resulting in poor performance. Since we have a static model list in Instill Cloud for now, we can implement a temporary workaround by caching the model list to improve performance.
This commit
- Implements a workaround to improve Instill Cloud performance.
> chore: implement a workaround to improve Instill Cloud performance

- pkg/service/service.go
Because
- The `uidAllowList` in `ListPipeline()` should not be nil.
This commit
- Fixes `uidAllowList` bug when listing pipeline.
> fix: fix `uidAllowList` bug when listing pipeline

- .env
- .github/workflows/coverage.yml
- Makefile
- cmd/init/main.go
- cmd/main/main.go
- cmd/migration/main.go
- cmd/worker/main.go
- config/config.go
- pkg/repository/repository_test.go
Because
- Repository layer has no coverage. We tend to rely on integration tests to verify this package communicates with the database correctly but these are expensive and should verify how each layer interconnects rather than covering all the behaviours of each layer.
- I set up these tests for [INS-4081](https://linear.app/instill-ai/issue/INS-4081/credit-data-model) as it has no high-level entrypoint (yet). The credit data model is being moved to `mgmt-backend` but having this functionality set up in `pipeline-backend` is still useful.
This commit
- Adds a simple test in `pkg/repository` that runs against a test DB. For that:
- A new database `pipeline_test` is created with the current migration in the local PostgreSQL database.
- Config initialisation takes a config path (so tests …
> feat: add repository tests against DB

- go.mod
- go.sum
- pkg/handler/secret.go
Because
- Originally, we used the `user/secrets` path for managing user secrets. However, this path style is not consistent with the pipeline endpoints. We should change it to `users/<userid>/secrets` for consistency.
This commit
- Adjusts the user secrets endpoint.
> chore: adjust secret endpoint

- .github/workflows/integration-test.yml
- go.mod
- go.sum
- integration-test/pipeline/const.js
- pkg/db/migration/convert/convert000013/main.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/worker/workflow.go
Because
- Originally, we used `${request.xxx}` to reference the pipeline input. We have decided to change it to `${trigger.xxx}` so that future event-based triggers can utilize the same reference.
This commit
- Uses `trigger` for the pipeline input reference.
> chore: use `trigger` for the pipeline input reference

- pkg/db/migration/convert/convert000013/main.go
Because
- The migration script caused the component ID to disappear.
This commit
- Fixes migration script.
> chore: fix migration script

- pkg/recipe/dag.go
Because
- We want to support hyphen in reference syntax like this `${openai-0.output.text[0]}` or `${trigger.my-value}`.
This commit
- Supports hyphen in reference syntax.
> feat: support hyphen in reference syntax

- pkg/service/convert.go
Because
- We missed a nil check in `includeIteratorComponentDetail()`.
This commit
- Fixes bug.
> chore: fix iterator bug

- pkg/middleware/interceptor.go
- pkg/middleware/interceptor_test.go
- pkg/repository/errors.go
- pkg/repository/repository.go
Because
- We should return a readable error message when creating a resource with a duplicated ID.
This commit
- Updates the error message for creating a duplicated resource.
> fix: update error message for creating duplicated resource

- pkg/service/pipeline.go
Because
- We didn't handle the nil value in the secrets query.
This commit
- Fixes trigger pipeline bug when the secret value is nil.
> fix: fix trigger pipeline bug when the secret value is nil

- pkg/recipe/dag.go
- pkg/recipe/memory.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/worker/main.go
- pkg/worker/workflow.go
Because
- Originally, we used a single key to read/write the trigger memory to/from Redis. When using the iterator, we needed to duplicate the component memory N times (N = size of the iteration batch). In the original implementation, this caused a lot of duplicated storage. For the duplicated data in the iterator memory, we should be able to use the same Redis key across the batch to get the data instead of duplicating the data.
This commit
- Uses combination keyset to read/write the trigger memory. This way, we can reuse the same data in the iteration instead of duplicating it.
> refactor: use combination keys to read/write the trigger memory

- pkg/recipe/memory.go
Because
- the memory purge function was accidentally commented out
This commit
- uncomments the memory purge function.
> chore: fix memory purge function

- integration-test/pipeline/const.js
Because
- We've added new HTTP endpoints without the `/core` and `/vdp` prefixes.
This commit
- Removes the `/core` and `/vdp` HTTP endpoint prefixes in HTTP integration test.
> test: remove /core and /vdp HTTP endpoint prefixes in integration test

- go.mod
- go.sum
- pkg/worker/workflow.go
Because
- We want the pipeline trigger context to be propagated to the component execution and usage handler.
This commit
- Adds a context param to Execute, Check and Collect.
- Makes system variables accessible at the UsageHandler methods.
> chore: add context to usage handler methods

- go.mod
- go.sum
- pkg/db/migration/convert/convert000013/main.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/service/secret.go
- pkg/utils/utils.go
Because
- We've introduced the secret management system. The naming is inconsistent with the `instillCredentialField` in the component JSON schema.
This commit
- Renames `instillCredentialField` to `instillSecret`.
> refactor: rename instillCredentialField to instillSecret

- cmd/worker/main.go
- go.mod
- go.sum
- pkg/usage/usage.go
- pkg/worker/main.go
- pkg/worker/workflow.go
Because
- We need a `PipelineUsageHandler` to collect the Instill Credit usage in the Cloud version.
This commit
- Adds a `PipelineUsageHandler` interface and a dummy `pipelineUsageHandler`.
> feat: add pipelineUsageHandler

- go.mod
- go.sum
- integration-test/pipeline/rest-component-definition.js
- pkg/handler/pipeline.go
- pkg/repository/base.go
- pkg/repository/repository.go
- pkg/repository/utils.go
- pkg/service/main.go
- pkg/service/pipeline.go
Because
- We want users to have a better UX in pipeline main page.
This commit
- frontend can pass order_by to make the pipeline sorted according to the params.
> feat: support sorting pipelines options by id and update_time

- go.mod
- go.sum
- pkg/datamodel/datamodel.go
- pkg/handler/pipeline.go
- pkg/repository/repository.go
- pkg/service/main.go
- pkg/service/pipeline.go
Because
- We'll provide a helper endpoint that returns metadata that Instill Hub needs.
This commit:
- Adds hub-stats endpoints.
> feat: implement hub-stats endpoint

- cmd/init/definitionupdater/updater.go
- cmd/init/definitionupdater/updater_test.go
- cmd/init/main.go
Because
- Component definition update logic is duplicated in Cloud. This caused a bug when both versions became out of sync.
This commit
- Exports logic so changes are propagated to Cloud.
> chore: export component definition update logic

- config/config.go
- go.mod
- go.sum
- pkg/recipe/variable.go
- pkg/service/convert.go
- pkg/service/pipeline.go
Because:
- Originally, we had a config called `UseStaticModelList` to speed up the Instill Model connector. However, with the introduction of the Instill Model cloud allowing users to upload models, this config is no longer needed.
- In the Instill Model connector, the component definition is dynamically generated by sending a request to Instill Model to get the model list, which incurs extra communication time. To minimize the impact on our system, we introduce a new parameter called `useDynamicDef` to indicate whether we want to use the dynamic definition or not. We will turn it off in the ListPipelines endpoint since it does not require the dynamic definition.
This commit:
- Removes the `UseStaticModelList` config.
- Introduces the `useDynamicDef` function parameter.
> refactor: remove UseStaticModelList workaround

- pkg/datamodel/datamodel.go
- pkg/service/convert.go
Because
- Originally, we didn't check the type for iterator in the recipe.
This commit
- Checks iterator type in the recipe.
> chore: check iterator type in the recipe

- pkg/handler/pipeline.go
- pkg/service/convert.go
Because
- The Console needs to show the owner profile. Currently, only using `VIEW_FULL` can return the profile, but it makes the payload size too big. So, we'd like to return the owner profile when using `VIEW_BASIC`.
- The recipe validation function doesn't work properly and prevents users from releasing a pipeline.
This commit
- Returns the owner in the pipeline response when using `VIEW_BASIC`.
- Removes recipe validation in pipeline release as a temporary solution.
> chore: return the owner in pipeline response when using VIEW_BASIC

- pkg/service/component_definition.go
Because
- Some content in the component definition can be dynamically generated when the backend knows who the user is.
This commit
- Returns dynamic component definitions in the definition endpoints.
> feat: return dynamic component definition in definition endpoints

- cmd/main/main.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/worker/workflow.go
Because
- In the dynamic component definition, we might need to use the secret value to generate the dynamic definition. Therefore, we need to render the secret value for this.
This commit
- Renders the secret value when using dynamic definition.
> feat: render secret value when using dynamic definition

- cmd/migration/main.go
- config/config.yaml
- go.mod
- go.sum
- pkg/datamodel/datamodel.go
- pkg/db/migration/000016_init.down.sql
- pkg/db/migration/000016_init.up.sql
- pkg/db/migration/convert/convert000016/main.go
- pkg/recipe/dag.go
- pkg/repository/repository.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/service/secret.go
- pkg/service/validator.go
- pkg/worker/workflow.go
Because
- To introduce "recipe as code", we will adopt YAML as the recipe format. YAML offers advanced features that JSON does not, such as the ability to include comments. We will gradually transition VDP to use YAML recipes.
This commit
- Recipes are now stored as YAML in the database. However, since the frontend has not yet adopted this format, we will continue to convert the recipes to JSON for the HTTP/gRPC API for now. We utilize GORM hooks to perform the JSON to YAML conversion.
- The datamodel has been simplified to facilitate easier marshaling/unmarshaling between struct, JSON and YAML.
> feat: store recipe as YAML

- cmd/main/main.go
- integration-test/pipeline/grpc-pipeline-public.js
- integration-test/pipeline/grpc.js
- integration-test/pipeline/rest-component-definition.js
- integration-test/pipeline/rest-connector-definition.js
- integration-test/pipeline/rest-operator-definition.js
- integration-test/pipeline/rest-pipeline-private.js
- integration-test/pipeline/rest-pipeline-public.js
- integration-test/pipeline/rest.js
- pkg/datamodel/datamodel.go
- pkg/service/convert.go
Because
- Currently, our API HTTP request and response bodies are a mix of camelCase and snake_case, which is not consistent.
This commit
- Uses camelCase for HTTP bodies.
> feat: use camelCase for HTTP body

- pkg/repository/repository.go
- pkg/service/convert.go
Because
- The `ConvertPipelineReleaseToPB` function is not working correctly.
This commit
- Fixes the pipeline release bug.
> chore: fix pipeline release bug

- integration-test/pipeline/grpc-pipeline-private.js
- integration-test/pipeline/grpc-pipeline-public.js
- integration-test/pipeline/rest-component-definition.js
- integration-test/pipeline/rest-connector-definition.js
- integration-test/pipeline/rest-operator-definition.js
- integration-test/pipeline/rest-pipeline-private.js
- integration-test/pipeline/rest-pipeline-public.js
- integration-test/pipeline/rest.js
- pkg/handler/pipeline.go
- pkg/repository/repository.go
- pkg/repository/transpiler.go
- pkg/service/component_definition.go
Because
- We should use camelCase for query strings to align with the HTTP body.
This commit
- Updates query strings `filter` and `orderBy` to use camelCase.
Note:
- We should further extract the common code in the `filter` and `orderBy` parsers into a shared function in the future.
> feat(endpoints): use camelCase for `filter` and `orderBy` query strings

- pkg/worker/workflow.go
Because
- The component condition field has a bug and always returns an error.
This commit
- Resolves the issue with the component condition not working.
> fix: resolve the issue with the component condition not working

- pkg/service/convert.go
Because
- The dynamic definition has a bug when the `component.Input` is nil.
This commit
- Fixes the dynamic definition bug.
> chore: fix dynamic definition bug

- Makefile
- go.mod
- go.sum
- pkg/repository/repository.go
Because
- The `pageToken` is not correctly encoded due to the refactor to camelCase.
This commit
- Fixes the `pageToken` bug.
> chore: fix pageToken bug

- pkg/service/errors.go
**Because**
- The typo fix ensures the documentation and error messages are accurate and clear.
**This commit**
- Corrects the syntax from `${secrets.my-secret}` to `${secret.my-secret}` to ensure proper referencing.
> chore: fix typo in errmsg plain text secret

- go.mod
- go.sum
- integration-test/pipeline/const.js
- integration-test/pipeline/grpc-pipeline-private.js
- integration-test/pipeline/grpc-pipeline-public-with-jwt.js
- integration-test/pipeline/grpc-pipeline-public.js
- integration-test/pipeline/grpc-trigger-async.js
- integration-test/pipeline/grpc-trigger.js
- integration-test/pipeline/rest-pipeline-private.js
- integration-test/pipeline/rest-pipeline-public-with-jwt.js
- integration-test/pipeline/rest-pipeline-public.js
- integration-test/pipeline/rest-trigger-async.js
- integration-test/pipeline/rest-trigger.js
- integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline_public_service.proto
- pkg/datamodel/datamodel.go
- pkg/handler/pipeline.go
- pkg/recipe/dag.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/service/secret.go
- pkg/service/validator.go
- pkg/worker/workflow.go
Because
- We are going to support pipeline recipes in YAML format. We will return the recipe in YAML format in the response and also allow users to create/update recipes using YAML format.
- Previously, we converted the component definition ID in the recipe into UID when writing it to the database. Now, since we will directly store this raw recipe in the database, we won't do this conversion anymore. In the future, we'll migrate recipes if the component definition ID changes.
This commit
- Exposes the `raw_recipe` field in the pipeline and pipeline_release endpoints, the original `recipe` in JSON format is still workable.
- Removes the component definition ID to UID conversion when reading/writing the recipe from/to the database.
Note
- Regarding the component definition ID to UID …
> feat: allow user to store recipe in YAML format

- pkg/acl/acl.go
- pkg/constant/constant.go
- pkg/datamodel/datamodel.go
- pkg/errors/errors.go
- pkg/handler/pipeline.go
- pkg/handler/utils.go
- pkg/middleware/interceptor.go
- pkg/middleware/interceptor_test.go
- pkg/recipe/variable.go
- pkg/service/convert.go
- pkg/service/errors.go
- pkg/service/pipeline.go
- pkg/service/utils.go
Because
- Users can provide the `Instill-Requester-Uid` in order to trigger pipelines on
behalf of an organization.
This commit
- Limits the execution permissions when an organization namespace is used to
trigger a pipeline (by release or ID, sync or async). It checks:
- User can impersonate the organization
- If an organization is the requester and doesn't own the pipeline, either the pipeline is public or a shareable link is used.
> feat: check trigger permissions when impersonating an organization

- pkg/db/migration/000017_init.down.sql
- pkg/db/migration/000017_init.up.sql
Because
- We will store the YAML recipe exactly as the user inputs it, and no longer convert the component definition ID to UID when writing the recipe to the database.
This commit
- Adds a migration script to update the existing recipes to use the component definition ID.
> chore: add migration script for YAML recipe

- cmd/init/main.go
- cmd/init/presetdownloader/downloader.go
- cmd/main/main.go
- config/config.go
- config/config.yaml
- pkg/datamodel/datamodel.go
- pkg/service/pipeline.go
Because
- In Instill Cloud, there is a special organization called `preset` that stores all preset pipelines available for users to use or clone. We also aim to make these preset pipelines available in Instill Core.
This commit
- Implements the functionality to download preset pipelines.
> feat: download preset pipelines from Instill Cloud

- cmd/init/presetdownloader/downloader.go
Because
- The network environment might prevent Instill Core from reaching Instill Cloud.
This commit
- Skips presetDownloader when Instill Cloud is unreachable.
> chore: skip presetDownloader when Instill Cloud is unreachable

- pkg/datamodel/datamodel.go
Because
- The component map wasn’t returned in the iterator when it was empty.
This commit
- Ensures that the map returns `{}` when empty to prevent a crash in the Console.
> fix: prevent a crash in Console caused by an empty map in iterator

- pkg/datamodel/datamodel.go
Because
- Previously, we stored the YAML recipe as a string without validating its format, which could lead to incorrect and broken data.
This commit
- Validates the YAML recipe before saving it.
> chore: validate YAML recipe before saving it

- integration-test/pipeline/rest-component-definition.js
- pkg/repository/transpiler.go
Because
- When performing fuzzy searches on pipelines and components, case-insensitivity should be allowed.
This commit
- Supports case-insensitive searches for pipelines and components.
> feat: support case-insensitive search for pipelines and components

- pkg/service/secret.go
Because
- We should block users from saving secret fields as plaintext in pipelines. The mechanism worked before, but in the recent revamp, we changed to store the component definition with ID instead of the UID in the recipe, which broke the mechanism.
This commit
> fix: block user saving secret fields as plaintext in pipeline

- go.sum
- pkg/middleware/middleware.go
Because
- We need to standardize the naming style.
This commit
- uses camelCase in SSE response.
> chore: use camelCase in SSE response

- cmd/init/presetdownloader/downloader.go
- cmd/worker/main.go
- go.mod
- go.sum
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/component_definition.go
- pkg/service/pipeline.go
- pkg/usage/usage.go
- pkg/worker/main.go
- pkg/worker/workflow.go
Because
- We have usage handlers for pipeline and component but the former only receives the number of components. We can merge them and simplify our logic.
This commit
- Removes the pipeline usage handler and injects only a component handler. The definition -> handler map is removed and the implementation is responsible of checking the component definition ID within its methods
> feat: inject single usage handler creator in components

- cmd/init/presetdownloader/downloader.go
- cmd/main/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/acl/acl.go
- pkg/datamodel/datamodel.go
- pkg/db/migration/000018_init.down.sql
- pkg/db/migration/000018_init.up.sql
- pkg/external/external.go
- pkg/middleware/middleware.go
- pkg/service/convert.go
Because
- We'll allow users to store some pipeline profile data, including `profile image`, `source_url`, `documentation_url`, and `license`.
This commit
- Follows the implementation from model-backend and adds `profile_image` and several profile fields for the pipeline.
- Updates the deprecated `grpc.Dial` to `grpc.NewClient`.
> feat: add profile_image and several profile fields for pipeline

- pkg/repository/repository.go
- pkg/service/pipeline.go
Because
- We use `featured` as a special tag in Instill Hub, users should not freely tag pipelines with this tag.
This commit
- Defines a reserved tag list.
- Prevents users from tagging pipelines with a reserved tag.
> feat: prevent users from tagging pipelines with a reserved tag

- go.mod
- go.sum
- pkg/service/component_definition.go
Because
- Clients can retrieve the definition of the Instill Model component with dynamic definition, which can be slow. Originally, regardless of how the operator/connector-definition endpoint was requested, the Instill model component always used dynamic definitions, resulting in slow response times in Console.
This commit
- Optimizes the performance of the definition endpoint by returning dynamic definitions only when necessary.
> refactor: optimize the performance for definition endpoint

- pkg/repository/repository.go
- pkg/repository/utils.go
Because
- The pageToken wasn't correctly encoded when ordering by certain fields.
This commit
-  Fixes pageToken not working when ordering by certain fields
> fix: fix pageToken not working when ordering by certain fields

- pkg/service/pipeline.go
Because
- End-user error messages should only be added when a Temporal error contains a message.
- The stream endpoint wasn't updated with the temporal [error message fix](https://github.com/instill-ai/pipeline-backend/pull/543).
This commit
- Updates the temporal error parsing in the `service` package.
> fix: parse end-user errors on stream trigger endpoint

- pkg/utils/utils.go
- pkg/worker/utils.go
- pkg/worker/workflow.go
Because
- In the dashboard, we'll want to display the triggers requested by a namespace (right now we're displaying the triggers on pipelines owned by the namespace). Therefore, we need to add the requester information to the metrics.
This commit
- Adds requester information to pipeline metrics
- Additionally, all the data we might filter / group by is sent as tags. Right now these are fields (not indexed on InfluxDB). When queried, the data is pivoted in order to filter and group.
> feat: add requester information to pipeline metrics

- .github/workflows/images.yml
- .github/workflows/integration-test.yml
- cmd/init/presetdownloader/downloader.go
- go.mod
- go.sum
- integration-test/proto/core/mgmt/v1beta/metric.proto
- integration-test/proto/core/mgmt/v1beta/mgmt.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_private_service.proto
- integration-test/proto/core/mgmt/v1beta/mgmt_public_service.proto
- integration-test/proto/core/mgmt/v1beta/protoc-gen-openapiv2/options/openapiv2.proto
- integration-test/proto/vdp/pipeline/v1beta/common.proto
- integration-test/proto/vdp/pipeline/v1beta/component_definition.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline_private_service.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline_public_service.proto
- integration-test/proto/vdp/pipeline/v1beta/protoc-gen-openapiv2/options/openapiv2.proto
- integration-test/proto/vdp/pipeline/v1beta/secret.proto
- pkg/handler/formdata_handler.go
- pkg/mock/repository_mock.gen.go
- pkg/service/convert.go
- pkg/usage/usage.go
Because
- Previously, we used a general `name` parameter in request parameters, e.g., `{name=users/*}`, which was ambiguous.
This commit
- Uses explicit `user_id` and `organization_id` in request parameters.
- Removes unnecessary environment variables.
> feat: use explicit `user_id` and `organization_id` in mgmt request

- go.mod
- go.sum
- pkg/handler/fieldannotation.go
- pkg/handler/main.go
- pkg/handler/pipeline.go
- pkg/handler/secret.go
- pkg/handler/utils.go
- pkg/middleware/middleware.go
- pkg/mock/mgmt_private_service_client_mock.gen.go
- pkg/resource/resource.go
- pkg/service/convert.go
- pkg/service/main.go
- pkg/service/utils.go
Because
- We'd like to simplify the API endpoints by merging users and organization endpoints into namespace endpoints.
This commit
- Introduces new namespace endpoints.
> feat: implement namespace endpoints

- go.mod
- go.sum
- pkg/handler/pipeline.go
Because
- We should avoid using ambiguous name parameter in operation endpoint requests.
This commit
- Uses explicit `operation_id` for GetOperation endpoint.
> chore: use explicit operation_id for GetOperation endpoint

- go.mod
- go.sum
Because
- we want to make vdp process all types of unstructured data
- we use ffmpeg to process the video
This commit
- add ffmpeg-go package in component
p.s.
ffmpeg is added in Dockerfile and Dockerfile.dev in audio pr, so we do not add them here to avoid confliction
> feat: add ffmpeg-go package for video operator

- go.mod
- go.sum
- pkg/db/migration/convert/convert000021/convert.go
- pkg/db/migration/migration.go
Because
- We recategorized TASK_CONVERT_TO_TEXT from text operator to document operator.
This commit
- Adds migration script for `TASK_CONVERT_TO_TEXT`.
> chore: add migration script for TASK_CONVERT_TO_TEXT

- go.mod
- go.sum
- pkg/service/component_definition.go
- pkg/service/convert.go
Because
- We are introducing a new generic component type.
This commit
- Supports the new generic component type in the deprecated connector-definition endpoints, as Console is still using them.
> chore: support generic component in connector-definition endpoints

- pkg/utils/utils.go
- pkg/worker/utils.go
Because
- The measurement introduced for the new dashboard endpoints introduced breaking changes that the clients haven't kept up with for this release.
This commit
- Restores the old measurement and sends the new one with a different measurement name in order to keep backwards-compatible and start filling information before the new dashboard is ready.
- Because the measurement name is changed, this commit shouldn't be reverted for the new dashboard implementation, only the deprecated method should be deleted.
> fix: send old and new pipeline trigger measurements

- Dockerfile
Because
- The ffmpeg installation was failed.
This commit
- Fixes wrong ffmpeg installation.
> chore: fix wrong ffmpeg installation

- Dockerfile
Because
- test failed at d0 with the dependency we installed to reduce the image size
This commit
- change back to the original dependency with full version of libreoffice
> fix: change the dependency to fix bugs

- pkg/handler/pipeline.go
Because
- The pipeline release trigger endpoint return empty response.
This commit
- Fixes empty response bug.
> chore: fix pipeline release no response bug

- pkg/service/pipeline.go
- pkg/worker/workflow.go
Because
- The pipeline can not be triggered when there are more than one iterator.
This commit
- Fixes pipeline could not have more than one iterator.
- Adjusts run-on-schedule setting.
> fix: fix pipeline could not have more than one iterator

- pkg/repository/transpiler.go
Because
- The SQL transpiler is not working correctly when using the AND operation.
This commit
- Fixes the SQL transpiler bug.
> fix: fix SQL transpiler bug

- Dockerfile
- Dockerfile.dev
- go.mod
- go.sum
Because:
- The `pdf2md` provide a better result for PDF to Markdown conversion.
This commit:
- Includes `pdf2md` in Dockerfile.
- Updates component package.
> feat: use pdf2md in document operator

- Dockerfile
Because
- `go-fitz` not being able to be built into a binary,
This commit
- Fixes the issue by adding the necessary Go build tags.
> fix: fix go-fitz not being able to be built into a binary

- go.mod
- go.sum
- pkg/datamodel/runlogging.go
- pkg/db/migration/000022_run_logging.down.sql
- pkg/db/migration/000022_run_logging.up.sql
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
Because
- we need to store run logging data
This commit
- added data model, migration SQL, repo functions
tested locally with below and passed
``` bash
go test -v ./... -tags dbtest -run TestRepository_UpsertPipelineRun
```
> feat(run): run logging data model & repo func

- pkg/handler/triggerhandler.go
- pkg/service/convert.go
Because
- The GET pipeline release APIs didn’t return the raw recipe.
- Streaming wasn’t working for pipeline releases.
This commit
- Fixes the issue where the pipeline release didn’t return the raw recipe.
- Resolves the streaming issue with pipeline release triggers.
> fix: return raw recipe for pipeline release

- cmd/main/main.go
- go.mod
- go.sum
- pkg/constant/constant.go
- pkg/data/array.go
- pkg/data/audio.go
- pkg/data/boolean.go
- pkg/data/bytearray.go
- pkg/data/data.go
- pkg/data/document.go
- pkg/data/file.go
- pkg/data/image.go
- pkg/data/map.go
- pkg/data/null.go
- pkg/data/number.go
- pkg/data/string.go
- pkg/data/video.go
- pkg/datamodel/datamodel.go
- pkg/handler/main.go
- pkg/handler/triggerhandler.go
- pkg/memory/memory.go
- pkg/middleware/middleware.go
- pkg/middleware/misc.go
- pkg/recipe/dag.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/service/secret.go
- pkg/worker/io.go
- pkg/worker/workflow.go
Because
- Previously, the streaming API didn’t return any error messages and didn’t support partial errors. If one component failed, the entire pipeline would fail. This design isn’t ideal, as other components should still be able to execute if they are not downstream of the failed component.
This commit
- Returns error messages in the stream.
- Allows partial errors in pipeline triggers and includes error messages in the metadata.
> feat: return error message when using streaming

- pkg/handler/pipeline.go
Because
- We want to enable the Console to filter pipelines by `numberOfRuns` and `numberOfClones`.
This commit
- Adds support for filtering by `numberOfRuns` and `numberOfClones`.
> feat: add support for filtering by numberOfRuns and numberOfClones

- go.mod
- go.sum
- pkg/handler/triggerhandler.go
- pkg/memory/memory.go
- pkg/worker/workflow.go
Because
- The original events were not well-designed for frontend use.
This commit
- Refactors the event codebase.
- Returns component status in all component events.
> feat: return component status in all component events

- Makefile
- pkg/data/array.go
- pkg/data/audio.go
- pkg/data/boolean.go
- pkg/data/bytearray.go
- pkg/data/convert.go
- pkg/data/data.go
- pkg/data/document.go
- pkg/data/file.go
- pkg/data/image.go
- pkg/data/map.go
- pkg/data/null.go
- pkg/data/number.go
- pkg/data/string.go
- pkg/data/utils.go
- pkg/data/video.go
- pkg/memory/memory.go
Because
- We introduced data structures for unstructured data, and we want users to easily access the data and perform format conversions.
This commit
- Refactors the reference system.
- Adds support for data properties and format conversions. For example, users can get the image width via `${some-component.image.width}` or convert a PDF to markdown via `${variable.document.markdown}`.
> feat: add supports for Data properties

- go.sum
- pkg/data/array.go
- pkg/data/map.go
- pkg/worker/workflow.go
Because
- The workflow timeout was set to the wrong value.
- The Map and Array didn’t handle errors properly.
This commit
- Fixes the bugs.
> fix: the workflow timeout is using wrong value

- cmd/worker/main.go
- pkg/worker/main.go
- pkg/worker/workflow.go
Because
- We cannot put time-consuming database operations directly in the Temporal workflow.
This commit
- Adds the missing `UpsertPipelineRunActivity`
> chore: add `UpsertPipelineRunActivity` for pipeline run logging

- Makefile
- go.mod
- go.sum
- pkg/handler/pipeline.go
- pkg/worker/workflow.go
Because
- Temporal Activities will result in errors if they aren't finished before the Workflow is completed
This commit
- Ensures Temporal Activities are completed before the Workflow is marked as completed
- Fixes a pipeline recipe update bug.
- Reverts wrong Makefile commit.
> chore: ensure Temporal Activities are completed before Workflow completed

- pkg/datamodel/datamodel.go
- pkg/service/convert.go
- pkg/service/pipeline.go
Because
- In the new low-code editor design, we want to improve user experience by allowing users to store any recipe they create, even if it's not a valid YAML recipe. This is especially beneficial for the auto-save feature, as we can't expect users to always write valid YAML in the editor.
This commit
- Allows storing invalid YAML recipes.
> feat: allow storing illegal YAML recipes

- cmd/worker/main.go
- pkg/handler/pipeline.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/worker/main.go
- pkg/worker/minioactivity.go
- pkg/worker/workflow.go
Because
- Temporal Sessions only work for Activities, and we can't ensure that Temporal Workflow and Activities run in the same worker.
This commit
- Moves all workflow memory operations into Temporal Activities.
- Allows `nil` DataSpecification for pipeline runs, as some recipes may not be valid and can't produce a DataSpecification.
- Removes unnecessary logs and warnings.
> refactor: move all workflow memory operations into Temporal Activities

- go.mod
- go.sum
- pkg/mock/converter_mock.gen.go
- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/worker/workflow.go
Because
- The run-logging API errors when there’s an iterator in the log.
- The iterator workflow uses incorrect workflow memory.
This commit
- Fixes the iterator memory and run-logging bugs.
> chore: fix iterator memory and run-logging bug

- pkg/worker/workflow.go
Because
- A component-run write operation was not removed from the Temporal workflow.
This commit
- Removes the redundant component-run write operation.
> chore: remove redundant component-run write operation

- go.mod
- go.sum
- pkg/service/convert.go
Because
- The recipe parsing in the pipeline release was incorrect
This commit
- Fixes the bug
- Updates the component package.
> chore: fix wrong recipe parsing in pipeline release

- go.mod
- go.sum
- pkg/data/data.go
Because
- The `NewValueFromStruct` function didn’t handle nil values properly.
This commit
- Updates the component package.
> chore: fix null data value bug

- integration-test/pipeline/rest-integration.js
- pkg/handler/integration.go
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/integration.go
- pkg/service/main.go
Because
- After creation, users need to get the information of a connection.
This commit
- Add GetConnection endpoint.
> feat(integration): add GetConnection endpoint

- pkg/service/pipeline.go
after review again, the temporalClient would be assigned in main function, so it would never be nil
> chore(service): remove unnesssary condition check

- pkg/usage/usage.go
Because
- pipeline id is missing for organization pipeline usage records
This commit
- add missing id for organization pipeline usage records
resolves INS-6180
> chore(usage): add missing id for org pipeline usage

- cmd/init/presetdownloader/downloader.go
Because
- The sharing config of the Instill Cloud preset pipelines should not be downloaded.
This commit
> fix: reset the preset pipeline sharing setting

- integration-test/pipeline/rest-integration.js
- integration-test/pipeline/rest.js
- pkg/handler/integration.go
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/service/integration.go
- pkg/service/main.go
Because
- The integration settings page contains a list of the pipelines referenced by each connection.
This commit
- Adds an endpoint to fetch this information, paginated. The implementation is rather dummy and inefficient, performance will be improved in a separate ticket.
> feat(integration): list pipeline IDs by connection reference

- go.mod
- go.sum
- pkg/recipe/dag.go
- pkg/service/pipeline.go
- pkg/worker/io.go
- pkg/worker/workflow.go
Because
- Previously, our component `Execute` interface did not handle batch processing well, particularly with error handling. If one data item encountered an error, the entire batch would fail. This is not ideal since each data item in the batch should be executed independently.
- When a component encounters an error, downstream components should be skipped.
This commit
- Adopts the new `Execute()` interface for more fine-grained error logging.
- Skips a component if its upstream components contain errors.
> refactor: adopt new component Execute() interface

- pkg/recipe/dag.go
Because
- The `Render()` function should return `data.Null` instead of `nil`.
This commit
- Fixes this bug.
> chore: fix nil value render bug

- Dockerfile
- Dockerfile.dev
Because
- pdf2md is temp solution
This commit
- take out the dependency for pdf2md
> chore(document): take out the unnecessary dependency

- go.mod
- go.sum
Because
- A new version of component has been released
This commit
- Updates `component` to v0.27.0-beta
> chore: bump component package

- .env
- .github/CONTRIBUTING.md
- Makefile
Because
- The names of these variables are similar but they have different uses (coverage vs integration tests).
This commit
- Documents such variables.
> chore(test): document DB_HOST and TEST_DBHOST variables

- Dockerfile
Because
- there is no tessdata when we install tesseract-ocr
This commit
- curl traineddata to get data for English version
> fix(document): fix bugs about image to text

- go.mod
- go.sum
- pkg/service/convert.go
Because
- We need to return the webhook endpoint URLs in the pipeline response so Console can display them to users.
This commit
- Adds the `endpoints` field to the pipeline response.
> feat: add `endpoints` field in pipeline response

- Makefile
- pkg/data/data.go
- pkg/service/pipeline.go
Because
- The pipeline share-code changes every time the pipeline is saved.
This commit
- Makes the pipeline share-code immutable
> fix: make the pipeline share-code immutable

- pkg/service/convert.go
Because
- The backend can not return pipeline release.
This commit
- Fixes pipeline release response error
- Fixes wrong pipeline release webhook endpoints
> chore: fix pipeline release response error

- pkg/service/pipeline.go
Because
- Some headers were missing in the webhook request.
This commit
- Fixes the incorrect `user-uid` and `requester-uid` in the webhook request.
- Updates the reference syntax for event messages. Users now need to use `${on.event.xxx}` instead of `${event.xxx}`.
> chore: fix wrong user-uid and requester-uid for webhook request

- pkg/memory/memory.go
- pkg/service/pipeline.go
Because
- We can directly remove the workflow memory in Redis after the trigger is completed.
This commit
- Purges the pipeline workflow memory in Redis after the trigger is completed.
> chore: purge pipeline workflow memory in Redis after the trigger is completed

- integration-test/pipeline/rest-integration.js
- integration-test/pipeline/rest-trigger.js
- pkg/recipe/connection.go
- pkg/recipe/dag.go
- pkg/service/convert.go
- pkg/worker/workflow.go
Because
- In order to resolve the reference to a connection when triggering a pipeline, all the connections were loaded to memory.
This commit
- Inspects the setup of the components in the recipe and loads only the required connections.
This will cause an error with a proper message when triggering a pipeline with an invalid reference:
```sh
$ curl -X POST 'http://localhost:8080/v1beta/namespaces/admin/pipelines/github-test/trigger' \
--header "Content-Type: application/json" \
--header "Authorization: Bearer instill_sk_KBcpJln4JfH0C0fVJm6ZLufaPzWnd8Fc" \
--data '{
"inputs": [
{
"prompt": "What are the pokemon types of Charizard? Answer with a comma-separated list of values that I can parse from a script. No formatting, no surrounding explanations, please."
}
]
}' | jq
% Total    % …
```
> feat(integration): load only connections present in the recipe and just once

- cmd/worker/main.go
- pkg/worker/main.go
- pkg/worker/workflow.go
Because
- Errors outside of `ComponentActivity` don't close the SSE connection, leaving the request hanging.
This commit
- Defers the `PipelineClosed` event and the workflow memory purge at the end of the trigger workflow.
- This effectively handles both error and success scenarios.
- Wraps `PreTriggerActivity` errors in a handler that sends a pipeline update event.
- In order to return the error in the response, we'll need to implement the `PipelineErrorUpdated` event.
> fix(streaming): close connection and purge workflow memory at the end of the trigger workflow

- go.mod
- go.sum
- pkg/service/convert.go
Because:
- We generate the field schema in the output based on the component schema, but not all schemas have the `instillFormat`. Some schemas use JSON or other indeterministic formats.
This commit:
- Uses `JSON` as the fallback `instillFormat` for these indeterministic fields.
> fix: the output schema is incorrect when there is an indeterministic instillFormat

- pkg/service/integration.go
Because
- https://github.com/instill-ai/protobufs/pull/475 removes `protoc-gen-validate` because it breaks the generated code used in the Python SDK.
This commit
- Removes the dependencies from that package.
> fix(proto): remove protoc-gen-validate dependencies

- go.mod
- go.sum
- pkg/component/operator/image/v0/README.mdx
- pkg/component/operator/image/v0/config/definition.json
- pkg/component/operator/image/v0/config/tasks.json
- pkg/component/operator/image/v0/draw.go
- pkg/component/operator/image/v0/draw_test.go
- pkg/component/operator/image/v0/image.go
- pkg/component/operator/image/v0/main.go
- pkg/component/operator/image/v0/task_concat.go
- pkg/component/operator/image/v0/task_concat_test.go
- pkg/component/operator/image/v0/task_crop.go
- pkg/component/operator/image/v0/task_crop_test.go
- pkg/component/operator/image/v0/task_draw_classification.go
- pkg/component/operator/image/v0/task_draw_classification_test.go
- pkg/component/operator/image/v0/task_draw_detection.go
- pkg/component/operator/image/v0/task_draw_detection_test.go
- pkg/component/operator/image/v0/task_draw_instance_segmentation.go
- pkg/component/operator/image/v0/task_draw_instance_segmentation_test.go
- pkg/component/operator/image/v0/task_draw_keypoint.go
- pkg/component/operator/image/v0/task_draw_keypoint_test.go
- pkg/component/operator/image/v0/task_draw_ocr.go
- pkg/component/operator/image/v0/task_draw_ocr_test.go
- pkg/component/operator/image/v0/task_draw_semantic_segmentation.go
- pkg/component/operator/image/v0/task_draw_semantic_segmentation_test.go
- pkg/component/operator/image/v0/task_resize.go
- pkg/component/operator/image/v0/task_resize_test.go
This is a port of https://github.com/instill-ai/component/pull/380
Because
- the Image operator requires `crop`, `resize`, and `concat` function
This commit
- implement the functions
- refactor the code and adopt the latest `concurrentExecutor`
> feat(image): add basic operation tasks

- pkg/component/base/formats.go
- pkg/service/convert.go
Because
- Instill Format Validator could not validate JSON-type data.
- We could not generate the correct DataSpecification for JSON-type data.
This commit
> fix: Instill Format validator can not validate JSON type data

- pkg/component/tools/compogen/go.mod
- pkg/component/tools/compogen/go.sum
Because
- A new version containging the `component` package has been released.
This commit
- Replaces the dependency with a commit SHA with a release version.
> chore(compogen): set pipeline-backend version to pinned release

- Makefile
- pkg/component/CONTRIBUTING.md
Because
- The component definition in the guideline lacks a type, which makes it not
show up in the console.
- Make command referenced in guidelines is different than the one in `Makefile`.
This commit
- Renames make command.
- Fixes definition in guidelines.
> chore(component): fix contribution guidelines and make command

- pkg/component/application/github/v0/README.mdx
- pkg/component/application/github/v0/config/tasks.json
- pkg/component/application/github/v0/issues.go
Because
- When creating issue using Github Component, Labels and Assignees field can be populated by providing github username and labels in input of component, which can be generated by AI components. Resolves instill-ai/instill-core#1095
This commit
- Add `Labels` and `Assignees` field in input for Create Issue Task.
> feat: Add assignees and labels support for create issue task in GitHub component

- pkg/datamodel/datamodel.go
- pkg/recipe/dag.go
- pkg/worker/utils.go
- pkg/worker/workflow.go
Because
- Currently, our iterator only implements the `foreach` function, meaning we iterate over the iterator `input`. This approach is insufficient for some use cases, where users may want to control the iteration's start and end points.
This commit
- Adds `range` support to the iterator implementation. It introduces the syntax `range: [start, stop [,step]]` to allow users to configure the iteration parameters. Additionally, users can specify the iteration index using `index: i`, with `i` being the default identifier.
> feat: add `range` support for iterator implementation

- pkg/datamodel/datamodel.go
- pkg/worker/utils.go
- pkg/worker/workflow.go
Because
- Readability decreases when using array representation for `range` with variable references. For example:
```yaml
range: [0, "${variable.top-k}", 1]
```
This commit
- Adds support for map representation, for example,
```yaml
range:
start: 0
stop: ${variable.top-k}
step: 1
```
> feat: support map representation for `range` in iterator

- pkg/service/convert.go
- pkg/service/pipeline.go
- pkg/utils/utils.go
Because
- The fallback mechanism failed when there was a subtype in the Instill Format. For example, when a component outputs `image/jpeg`, the Console could not successfully display the image.
This commit
- Fixes the fallback mechanism for handling Instill Format with subtypes.
> fix: the fallback mechanism for handling Instill Format with subtypes

- pkg/component/operator/json/v0/.compogen/extra-jq.mdx
- pkg/component/operator/json/v0/README.mdx
Because
- JQ doesn't support slashes in dictionary key names, which has caused some confusion.
This commit
- Document this pitfall and its workaround.
> chore(json): document pitfall in JQ filter

- config/config.yaml
- go.mod
- go.sum
- integration-test/pipeline/rest-integration.js
- integration-test/proto/vdp/pipeline/v1beta/integration.proto
- pkg/component/application/slack/v0/config/setup.json
- pkg/component/internal/mock/artifact_public_service_client_mock.gen.go
- pkg/datamodel/datamodel.go
- pkg/db/migration/000030_connection_identity.down.sql
- pkg/db/migration/000030_connection_identity.up.sql
- pkg/service/integration.go
- pkg/service/pipeline.go
- pkg/service/utils.go
Because
- When a user authorizes an Instill component using OAuth, we want to
display the identity that they used.
This commit
- Adds identity information to OAuth connections.
- Makes OAuth method the only accepted one for connections if it's
supported.
> feat(integration): add identity to OAuth connections

- pkg/component/ai/openai/v0/main.go
Because
- The OpenAI request timeout is too short for handling text generation effectively.
This commit
- Increases the OpenAI request timeout duration.
> chore(component): increase OpenAI request timeout

- Dockerfile
- Dockerfile.dev
- pkg/component/operator/web/v0/.compogen/scrape_webpage.mdx
- pkg/component/operator/web/v0/README.mdx
- pkg/component/operator/web/v0/config/tasks.json
- pkg/component/operator/web/v0/main.go
- pkg/component/operator/web/v0/scrape_webpage.go
Because
- there is a handshake error
- the page we target to scrape is dynamic
This commit
- before full investigation about why there is a handshake issue, we use curl to fetch the static content
- we add mock users' behaviours with scrolling down as a default
> feat(web): fix bug and add mock users' behaviours by chromedp

- Dockerfile
Because
- The `GODEBUG` is a runtime setting.
This commit
- Adjusts `GODEBUG` setting in Dockerfile
> chore: adjust GODEBUG setting in Dockerfile

- cmd/init/presetdownloader/downloader.go
- pkg/constant/constant.go
- pkg/repository/repository.go
Because
- Preset pipelines should be hided in `GET /pipelines` requests. These pipelines are used by the artifact backend and should not be directly exposed to users.
This commit
- hides preset pipelines in `GET /pipelines` requests
> chore: hide preset pipelines in `GET /pipelines` requests

- pkg/component/application/github/v0/config/setup.json
- pkg/repository/repository.go
Because
- GitHub component's `TASK_CREATE_ISSUE` didn't work with an OAuth connection.
This commit
- Updates the OAuth token scopes to allow issue creation / view.
- Additionally, updates the `ListPipelinesByConnectionID` endpoint to return only non-deleted pipelines.
> fix(integration): update GitHub scopes to read/write repository issues

- go.mod
- go.sum
- pkg/handler/pipeline.go
- pkg/service/main.go
- pkg/service/pipeline.go
Because
- Users should explicitly set the target namespace and pipeline ID when cloning a pipeline.
This commit
- Refactors parameters in the Clone API to support this functionality.
> feat: use explicit parameter for target namespace when cloning pipeline

- pkg/component/ai/universalai/v0/component_test.go
- pkg/component/ai/universalai/v0/config/definition.json
- pkg/component/ai/universalai/v0/config/setup.json
- pkg/component/ai/universalai/v0/config/tasks.json
- pkg/component/ai/universalai/v0/main.go
- pkg/component/ai/universalai/v0/text_chat_task.go
- pkg/component/ai/universalai/v0/text_chat_task_test.go
- pkg/component/base/execution_wrapper.go
- pkg/component/store/store.go
This is a port of https://github.com/instill-ai/component/pull/362
Because
- we will support universal ai to execute vendors' ai models
This commit
- import the vendors' key to component and execution
> feat(universalai): add instill credit function for universal ai component

- pkg/component/data/instillartifact/v0/artifact_operation.go
- pkg/component/data/instillartifact/v0/main.go
- pkg/recipe/dag.go
- pkg/worker/utils.go
- pkg/worker/workflow.go
Because
- We want to use the array index not only for bracket indexing but also as a variable.
This commit
- Adds support for referencing array indices as strings.
- Fixes instill-artifact client closing bug.
> chore: add support for referencing array indices as strings

- cmd/init/presetdownloader/downloader.go
Because
- The organization ID was incorrect when downloading the preset downloader.
This commit
> chore: fix preset downloader

- integration-test/pipeline/rest-integration.js
- pkg/component/application/slack/v0/config/setup.json
Because
- We're going to need 2 OAuth tokens for Slack, one for the Instill App bot
and another for the user.
This commit
- Temporarily removes the OAuth integration for Slack.
> chore(integration): temporarily remove Slack OAuth integration

- pkg/component/operator/document/v0/pdf_to_markdown/page_image_processor.py
Because
- we did not catch the error when the bbox is out of boundary
This commit
- catch the error
> fix(document): catch the error if the bbox is out of boundary

- go.mod
- go.sum
Because
- `x` has a new release tag.
This commit
- Update `x` dependency.
> chore(release): update x release

- pkg/memory/memory.go
Because
- The event for iterator input updates was not being sent.
This commit
> fix: fix event for iterator input updates was not being sent

- pkg/worker/workflow.go
Because
- The pipeline output streaming was not functioning properly.
This commit
> fix: fix he pipeline output streaming was not functioning properly

- pkg/component/base/formats.go
Because
- The InstillAcceptFormats doesn't works with collection component
This commit
- Fixes the bug
> fix: the InstillAcceptFormats doesn't works with collection component

- cmd/init/presetdownloader/downloader.go
- pkg/constant/constant.go
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/service/pipeline.go
Because
- We don't want to show preset pipelines in the `GET /pipelines` endpoint. Initially, we used a constant organization UID to filter them out, but in different deployments, the preset namespace UID can vary.
This commit
- Fixes the bug where preset pipelines were still visible in certain deployment environments.
> fix: hide preset pipelines in GET /pipelines endpoint

- pkg/component/application/instillapp/v0/app_operation.go
- pkg/component/store/store.go
- pkg/service/component_definition.go
Because
- instill app is only exposed to ee version
This commit
- exclude instill app when it is ce version
- initialise Instill App
- fix the bug in Instill App when end to end test
- chore the exported and non-exported functions
Note
- We should extend the OneOf function for output in the other PR in near future.
> feat(component): implement instill app features

- config/config.yaml
- pkg/component/application/slack/v0/.compogen/extra-setup.mdx
- pkg/component/application/slack/v0/README.mdx
- pkg/component/application/slack/v0/api_functions.go
- pkg/component/application/slack/v0/client.go
- pkg/component/application/slack/v0/component_test.go
- pkg/component/application/slack/v0/config/definition.json
- pkg/component/application/slack/v0/config/setup.json
- pkg/component/application/slack/v0/config/tasks.json
- pkg/component/application/slack/v0/main.go
- pkg/component/application/slack/v0/task_functions.go
- pkg/db/migration/convert/convert000019/convert.go
- pkg/db/migration/convert/convert000020/convert.go
- pkg/db/migration/convert/convert000021/convert.go
- pkg/db/migration/convert/convert000022/convert.go
- pkg/db/migration/convert/convert000024/convert.go
- pkg/db/migration/convert/convert000029/convert.go
- pkg/db/migration/convert/convert000031/convert.go
- pkg/db/migration/convert/converter.go
- pkg/db/migration/migration.go
Because
- Slack integration can send messages as either a user or a bot.
This commit
- Updates the component `setup` to hold both tokens.
> feat(slack): allow posting messages as user or bot

- pkg/handler/triggerhandler.go
Because
- There is a redundant `null` message at the end of streaming.
This commit
- Removes redundant message in streaming
> fix: remove redundant message in streaming

- pkg/service/pipeline_repository_test.go
Because
- lint fails in some unit test files
This commit
- fix the unit tests
> chore: fix unit tests

- pkg/component/store/store.go
Because
- we postpone the instill app release
This commit
- disable instill app component
> chore(component): disable instill app

- pkg/component/base/formats.go
Because
- The InstillFormat validator wasn't generating the correct InstillFormat for array items.
This commit
- Fixes the InstillFormat validation function.
> fix: fix InstillFormat validate function

- pkg/handler/pipeline.go
- pkg/service/pipeline.go
- pkg/service/pipeline_repository_test.go
- pkg/service/utils.go
Because
- list pipeline run should return results even if there is an error in minio
This commit
- log errors instead of return error
> fix(run): not return minio error in list pipeline run

- go.mod
- go.sum
- pkg/datamodel/runlogging.go
- pkg/handler/pipeline.go
- pkg/mock/acl_client_interface_mock.gen.go
- pkg/mock/converter_mock.gen.go
- pkg/mock/mgmt_private_service_client_mock.gen.go
- pkg/mock/minio_i_mock.gen.go
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/component_definition.go
- pkg/service/main.go
- pkg/service/pipeline.go
- pkg/service/utils.go
Because
- the data that users could see on dashboard are different from what they can see on Runs page in a single pipeline or model
This commit
- add new run logging API for dashboard
> feat(run): run logging data list by requester API

- pkg/component/ai/cohere/v0/config/definition.json
- pkg/component/ai/fireworksai/v0/config/definition.json
- pkg/component/ai/huggingface/v0/config/definition.json
- pkg/component/ai/instill/v0/config/definition.json
- pkg/component/ai/mistralai/v0/config/definition.json
- pkg/component/ai/openai/v0/config/definition.json
- pkg/component/ai/stabilityai/v0/config/definition.json
- pkg/component/ai/universalai/v0/config/definition.json
- pkg/component/application/googlesearch/v0/config/definition.json
- pkg/component/application/instillapp/v0/config/definition.json
- pkg/component/application/slack/v0/README.mdx
- pkg/component/application/slack/v0/config/tasks.json
- pkg/component/data/elasticsearch/v0/config/definition.json
- pkg/component/data/googlecloudstorage/v0/config/definition.json
- pkg/component/data/instillartifact/v0/config/definition.json
Because
- Documentation website paths follow the same convention as the IDs, not the Go packages.
- This PR is a prerequisite for doc generation in https://github.com/instill-ai/instill.tech/pull/1184.
This commit
- Updates the documentation URL references.
> feat(component): update documentation URL to component ID

- pkg/component/ai/groq/v0/config/tasks.json
Because
- The example model in the `groq` component (the one that will appear when adding a new component in the editor) doesn't support Instill Credentials (i.e. it requires a custom `setup.api-key`.
This commit
- Shows by default a model that supports credentials.
- Part of INS-6643
> fix(groq): use credential-supported model in example

- .github/CODEOWNERS
- Dockerfile
- Dockerfile.dev
- Makefile
Because
- there are confusing and unuseful Makefile targets
- the latest Docker version warns ENV syntax and default ARG value
This commit
- fixes the issues
- updates CODEOWNERS
> ci(Dockerfile,Makefile): refine targets and fix warnings

- pkg/component/CONTRIBUTING.md
Because
- `zap` isn't referenced in the sample code block
- the dev container should be removed to re-run from scratch during development
This commit
- fix accordingly
> docs(component): fix contribution guideline

- pkg/component/application/slack/v0/config/setup.json
Because
- Frontend is implementing OAuth 2.0 flow for the Slack component.
This commit
- Adds the OAuth information to the component.
> feat(slack): enable OAuth 2.0 integration

- pkg/component/operator/web/v0/README.mdx
- pkg/component/operator/web/v0/config/tasks.json
- pkg/component/operator/web/v0/crawl_website.go
- pkg/component/operator/web/v0/main.go
- pkg/component/operator/web/v0/main_test.go
- pkg/component/operator/web/v0/scrape_webpage.go
Because
- we want to increase max k
- we want to make scrape method explicit
This commit
- refactor crawler
- add scrape method for scraper
> feat(web): refactor web operator

- pkg/component/ai/embedding.go
- pkg/component/ai/instill/v0/README.mdx
- pkg/component/ai/instill/v0/config/definition.json
- pkg/component/ai/instill/v0/config/tasks.json
- pkg/component/ai/instill/v0/embedding.go
- pkg/component/ai/instill/v0/main.go
- pkg/component/ai/universalai/v0/config/tasks.json
- pkg/component/application/instillapp/v0/config/tasks.json
- pkg/component/tools/compogen/pkg/gen/readme.go
- pkg/component/tools/compogen/pkg/gen/schema.go
Because
- we need embedding from instill model
This commit
- add the standardised input & output for embedding
- add embedding to instill model
- support oneOf for the array items
> feat(instillmodel): implement instill model embedding

- pkg/component/application/slack/v0/.compogen/extra-setup.mdx
- pkg/component/application/slack/v0/README.mdx
Because
- The setup documentation on the Slack component is unclear about how OAuth 2.0 is used.
This commit
- Improves the OAuth documentation.
- Fixes INS-6658
> chore(slack): improve OAuth documentation

- pkg/repository/transpiler.go
- pkg/service/convert.go
- pkg/service/pipeline.go
Because
- We didn't apply any naming convention on tags
This commit
- Standardizes the tag naming convention to match the following criteria:
- All user-defined tags will be converted to lowercase.
- All system/reserved tags will be capitalized.
> feat: standardize the tag naming convention

- go.mod
- go.sum
- pkg/component/internal/mock/artifact_public_service_client_mock.gen.go
- pkg/handler/pipeline.go
- pkg/service/main.go
- pkg/service/pipeline_repository_test.go
- pkg/service/pipelinerun.go
Because
- console runs page needs to display requester
This commit
- expose requester id in pipeline runs response
> feat(run): add requester id in list pipeline run response

- pkg/component/operator/video/v0/video_operation.go
Because
- The Video Component minimum FPS is 1 (integer), For a use case like presentation in the video, we do not want to extract 1 frame every second but 1 frame every 10 seconds to save resources and reduce the number of images needed to feed into the next component. 
- Issue instill-ai/instill-core/issues/1115.
This commit
- Change FPS to accept real number inputs as well i.e. 60, 30, 1, 0.5, 0.2, 0.1 in both the tasks `TASK_SUBSAMPLE_VIDEO` and `TASK_SUBSAMPLE_VIDEO_FRAMES`.
- Also implements a string parsing function which can handle fractional inputs like 1/2 and 1/5 but is commented out - because the input `type` can only be defined as one single type (`number` or `string` and not both). The function can be used if this issue is resolved in the future.
> feat(component, video): implemented fractional fps value - fps as number, and added some debugging flags for ffmpeg

- pkg/component/generic/collection/v0/.compogen/bottom.mdx
- pkg/component/generic/collection/v0/README.mdx
- pkg/component/generic/collection/v0/config/definition.json
- pkg/component/generic/collection/v0/config/tasks.json
- pkg/component/generic/collection/v0/main.go
- pkg/component/generic/collection/v0/main_test.go
- pkg/component/generic/collection/v0/task_append.go
- pkg/component/generic/collection/v0/task_assign.go
- pkg/component/generic/collection/v0/task_concat.go
- pkg/component/generic/collection/v0/task_difference.go
- pkg/component/generic/collection/v0/task_intersection.go
- pkg/component/generic/collection/v0/task_split.go
- pkg/component/generic/collection/v0/task_union.go
Because
- it make pipeline easier to manipulate array
This commit
- add task split
> feat(collection): add task split

- go.mod
- go.sum
- integration-test/proto/vdp/pipeline/v1beta/integration.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline_public_service.proto
- pkg/handler/integration.go
- pkg/service/integration.go
- pkg/service/main.go
Because
- Namespace ID in connection requests was being read from the nested
object, which caused conflicts in the OpenAPI definitions.
This commit
- Reads the namespace ID as an explicit parameter. This field in the
Connection object becomes, then, an `OUTPUT_ONLY` field.
> chore(integration): read namespace ID from creation / update request, not object

- pkg/data/audio_test.go
Because
- The file URL in test cases used a link to the feature branch
This commit
- fixes the link
> chore: fix file url in audio test-cases

- pkg/recipe/dag.go
Because
- When a reference is present in the `range` field, the iterator fails to identify the correct upstreams.
This commit
- The pipeline should construct the correct DAG based on each component’s upstream dependencies.
> fix: fix iterator upstream check

- integration-test/pipeline/rest-integration.js
Because
- Integration tests are run from different repos (`instill-core`, `api-gateway`), and a dependency on an env variable was introduced.
This commit
- Disables the tests until all CIs have been updated to provide these variables. Alternatively, the affected tests can be optional and run only when a flag is provided.
> chore(test): disable OAuth integration tests temporarily

- pkg/data/bytearray.go
- pkg/data/file.go
- pkg/data/struct.go
Because
- The mp3 content-type was incorrect in the comment.
This commit
- Fixes the incorrect mp3 content-type
- Uses the built-in Equal function to compare byte arrays
> chore: fix wrong mp3 content-type

- pkg/component/generic/http/v0/component_test.go
- pkg/component/generic/http/v0/main.go
Because
- Previously, HTTP response data could include files, documents, images, videos, or audio, and assigning them to the correct Instill format was necessary for pipeline usability.
This commit:
- Automatically detects the file type when the response is in binary format.
> chore(component,http): auto-detect file type when the response is binary

- pkg/component/application/slack/v0/.compogen/extra-setup.mdx
Because
- https://github.com/instill-ai/instill-core/pull/1143/files changed the location to set the component environment variables.
This commit
- Fixes reference in Slack docs.
> fix(slack): correct link to OAuth config in documentation

- pkg/component/CONTRIBUTING.md
- pkg/component/application/slack/v0/README.mdx
- pkg/component/application/slack/v0/config/tasks.json
- pkg/data/data.go
Because
- we want to YYYY-MM-DD be able to parse in string type
This commit
- convert time to string
- add explanation in guideline
> feat: convert time type to string

- .github/CONTRIBUTING.md
- .github/workflows/golangci-lint.yml
- .pre-commit-config.yaml
- pkg/component/operator/audio/v0/.compogen/bottom.mdx
- pkg/component/operator/audio/v0/README.mdx
Because
- Previously, the pre-commit hooks failed due to an ONNXRuntime header issue.
This commit:
- Adds a guide to resolve the ONNXRuntime build issue during pre-commit
> chore: add guide to resolve ONNXRuntime build issue during pre-commit

- go.mod
- go.sum
- pkg/service/utils.go
Because
- dashboard needs pipeline/model namespace id to redirect
This commit
- add namespace id in response
> fix(run): add namespace id in response

- pkg/component/application/instillapp/v0/task_read_chat_history.go
Because
- artifact backend reply error when no app ID in DB
This commit
- return no error as long as not get the result
> fix: fix bug not to return error if there is no app or conversation

- pkg/data/audio.go
- pkg/data/document.go
- pkg/data/file.go
- pkg/data/format/format.go
- pkg/data/image.go
- pkg/data/utils.go
- pkg/data/video.go
- pkg/data/video_test.go
Because
- we want to standardize naming conventions across the codebase by using lowercase `filename` instead of camelCase `fileName`.
This commit
- replaces all instances of `fileName` with `filename`.
> chore: use `filename` instead of `fileName`

- .github/workflows/integration-test.yml
Because
- Build & push step is [failing](https://github.com/instill-ai/pipeline-backend/actions/runs/11739667642/job/32710453549) due to lack of disk space
```
#31 [linux/arm64 build  8/11] RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=linux GOARCH=arm64 go build -tags=ocr,onnx -o /pipeline-backend ./cmd/main
#31 1722.9 # github.com/instill-ai/pipeline-backend/cmd/main
#31 1722.9 /usr/local/go/pkg/tool/linux_arm64/link: mapping output file failed: no space left on device
#31 ERROR: process "/bin/sh -c GOOS=$TARGETOS GOARCH=$TARGETARCH go build -tags=ocr,onnx -o /${SERVICE_NAME} ./cmd/main" did not complete successfully: exit code: 1
------
> [linux/arm64 build  8/11] RUN --mount=target=. …
```
> fix(integration-test): maximize build space on image build & push

- .github/workflows/images.yml
Because
- Previous commit maximized the space only for the PR workflow, not the `images.yml` one.
- The other dependency, located on `instill-core`, already contains this step.
This commit
- Add space maximization step to `images.yml`.
> chore(integration-test): maximize build space on image build & push

- .github/workflows/semantic.yml
Because
- the codebase now includes additional components, it’s better for PRs to mention the specific scope.
This commit
- add PR title scope requirement.
> ci(workflows): add PR title scope check

- pkg/service/convert.go
Because
- A nil check is missing in includeIteratorComponentDetail()
This commit
- Fixes the bug by adding the necessary nil check.
> fix(service): add missing nil check in includeIteratorComponentDetail()

- pkg/data/number.go
- pkg/data/number_test.go
Because
- Previously, numberData only supported float data, making it difficult to determine whether to stringify it as an original float or integer.
This commit
- Refactors numberData to support both float and integer types.
> fix(data): refactor numberData to support both float and integer types

- pkg/datamodel/datamodel.go
- pkg/service/convert.go
- pkg/service/pipeline.go
Because
- Previously, we used the following format to set up the run-on-event and run-on-schedule recipes. For certain application events, we'll use a polling method to capture the event, which overlaps with the run-on-schedule functionality.
```
on:
event:
<event-id>:
type: slack
event: EVENT_NEW_MESSAGE
schedule:
<schedule-id>:
cron:
```
This commit
- merges run-on-event and run-on-schedule and refactors recipe structure to use the following new format
```
on:
<event-id>:
type: slack
event: EVENT_NEW_MESSAGE
config:
channel: xxx
setup: ${connection.xxx}
<schedule-id>:
type: schedule
event: EVENT_SCHEDULE
config:
schedule: 
cron: 
- '30 2 * * *' 
```
> feat(recipe): refactor run-on-event recipe structure

- config/config.yaml
- integration-test/pipeline/const.js
- integration-test/pipeline/rest-integration.js
- integration-test/pipeline/rest-trigger.js
- pkg/datamodel/datamodel.go
- pkg/db/migration/convert/convert000035/convert.go
- pkg/db/migration/convert/convert000036/convert.go
- pkg/db/migration/migration.go
- pkg/service/convert.go
- pkg/service/pipeline.go
Because
- We currently use the `instill-format` field to specify the format of variables in the recipe. But the `instill-` prefix is redundant now.
This commit
- Removes the `instill-` prefix, so the field name becomes `format`.
> feat(recipe): rename `instill-format` to `format`

- pkg/component/base/executionwrapper.go
- pkg/data/struct.go
Because
- we miss unit type
This commit
- add unit type when unmarshal
- add the logger in panic section for better debugging flow
> fix: fix bug about unit type

- pkg/component/operator/document/v0/convert_to_images_test.go
- pkg/component/operator/document/v0/transformer/const.go
- pkg/component/operator/document/v0/transformer/execution/get_page_numbers.py
- pkg/component/operator/document/v0/transformer/execution/task_convert_to_images.py
- pkg/component/operator/document/v0/transformer/images.go
Because
- it is slow when pdf to image
This commit
- make converter concurrently
> feat: convert pdf to image concurrently

- pkg/datamodel/datamodel.go
- pkg/service/convert.go
Because
- Console cannot adapt to the new schema at this time.
This commit
-  use `instillFormat` in API response for backward compatibility, but the user still need to use `format` in recipe.
> chore(recipe): use `instillFormat` in API response for backward compatibility

- pkg/component/application/github/v0/main.go
Because
- The content type for GitHub webhook registration was incorrect.
This commit
> chore(component,github): fix webhook registration

- Makefile
- cmd/main/main.go
- config/config.go
- pkg/external/external.go
- pkg/service/integration.go
- pkg/service/main.go
Because
- Certain OAuth integrations like Google Drive pass a review process. We need to test the scopes internally before making the app public.
This commit
- Adds a way to hide the OAuth integration for certain components and emails.
> chore(integration): whitelist certain user emails for certain integrations

- pkg/component/operator/document/v0/convert_to_images.go
Because
- there is a bug when converting doc to images
This commit
- trim base64 prefix
> fix(document): fix bug about convert to image

- pkg/repository/repository.go
- pkg/service/component_definition.go
Because
- Previously, the instill-app component was excluded, resulting in an empty item in the API response, which caused the Console to fail.
This commit
- skips empty component definition in API response
> fix(service): skip empty component definition in API response

- pkg/handler/triggerhandler.go
- pkg/service/pipeline.go
Because
- Previously, pipeline trigger errors were not streamed to users; only component errors were streamed.
This commit
- Implements the PipelineErrorUpdated streaming event to handle pipeline errors.
- Improves trigger variable validation.
Note
- This is a quick solution to capture and stream most errors. Some errors may still be excluded, requiring further optimization.
> feat(service): implement PipelineErrorUpdated streaming event for pipeline errors

- pkg/service/webhook.go
Because
- We want to place the event message under `on.event-id.message` instead of `on.event-id` to allow support for non-message data in the future.
This commit
- Wraps the event message within `on.event-id.message`.
> chore(service): wrap the event message in `on.event-id.message`

- pkg/component/application/github/v0/main.go
- pkg/component/base/component.go
- pkg/service/pipeline.go
Because
- The original webhook registration flow could cause conflicts when multiple pipelines register to the same repository.
This commit
- Adjusts the webhook registration flow to prevent conflicts.
> chore(component,github): adjust webhook registration flow

- pkg/data/struct.go
- pkg/external/external.go
Because
- Previously, we trusted the MIME type retrieved from MinIO or other data sources, which might be incorrect.
This commit
- Adds MIME type detection in the backend binaryFetcher.
> fix(service): add MIME type detection in the backend binaryFetcher

- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/worker/workflow.go
Because
- The API Gateway may operate in TLS-enabled mode. When uploading blob data, the data passes through the API Gateway. A configuration is needed to determine whether to connect via TLS.
This Commit
- Adds a tlsEnabled configuration for blob data uploads.
> chore(workflow): add tlsEnabled configuration for blob data uploads

- pkg/component/ai/openai/v0/main.go
- pkg/component/operator/document/v0/convert_document_to_markdown.go
Because
- We cannot convert a base64 string to a bytearray when it includes a MIME type prefix.
This Commit
- Trims the MIME type from the base64 string.
> chore(component): trim mime type in base64 string

- pkg/db/migration/convert/convert000036/convert.go
This commit
- fixes migration script for renaming instill-format
> chore(migration): fix migration script for renaming instill-format

- pkg/db/migration/convert/convert000036/convert.go
Because:
- The console no longer supports the `*/*` format.
This commit:
- Migrates the `*/*` format to `file`.
> chore(migration): migrate format `*/*` to `file`

- pkg/memory/memory.go
- pkg/recipe/dag.go
Because:
- Previously, component intermediate data was included in the pipeline response to inform users about pipeline activity. However, with the introduction of the pipeline run log, which provides access to this data, including it in the trigger response is redundant and adds significant latency.
This commit:
- Removes component intermediate data from the pipeline response.
> refactor(service): remove component intermediate data in pipeline response

- pkg/component/application/github/v0/README.mdx
- pkg/component/application/github/v0/component_test.go
- pkg/component/application/github/v0/config/tasks.json
- pkg/component/application/github/v0/issues.go
- pkg/component/application/github/v0/review_comment.go
- pkg/component/application/github/v0/utils.go
Because
- in ymal parser, we only provide date only string format
This commit
- convert GitHub DateTime input to DateOnly
Note
- We will need to find a solution about how to provide the Date and DateTime at the same time. Now, the current YAML parser cannot read the original users' input.
> fix(github): fix time format bug

- pkg/datamodel/datamodel.go
- pkg/service/convert.go
Because:
- We removed the instillUIOrder attribute for variable and output, but the Console still requires it for display.
This commit:
- Adds the instillUIOrder attribute back.
> chore(service): add instillUIOrder attribute for varialbe and outpu back

- pkg/component/application/github/v0/.compogen/bottom.mdx
- pkg/component/application/github/v0/README.mdx
- pkg/component/application/slack/v0/.compogen/bottom.mdx
- pkg/component/application/slack/v0/README.mdx
- pkg/component/application/slack/v0/config/events.json
- pkg/component/application/slack/v0/main.go
This commit
- adds documentation for events in Slack and GitHub components.
> docs(component,slack,github): add documentation for events

- pkg/data/file.go
- pkg/worker/workflow.go
Because
- The file extension is needed in the output filename to ensure MinIO downloads have a proper filename.
This commit
- Adds the file extension to the output filename.
- Removes unnecessary pointers to interfaces.
> feat(service): add the file extension to the output filename

- go.mod
- go.sum
- integration-test/pipeline/rest-integration.js
- integration-test/proto/vdp/pipeline/v1beta/common.proto
- integration-test/proto/vdp/pipeline/v1beta/component_definition.proto
- integration-test/proto/vdp/pipeline/v1beta/integration.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline_public_service.proto
- pkg/component/internal/mock/app_public_service_server_mock.gen.go
- pkg/service/integration.go
Because
- The `schemas` field was added under the wrong assumption that the
integration schemas would differ across connection methods (OAuth vs
key-value).
- After deprecating this field and providing an alternative
`setupSchema`
field, all the clients for the deprecated one have been removed.
Therefore, removing the deprecated field won't break any client.
This commit
- Removes the deprecated `schemas` field.
> chore(integration): remove deprecated `schemas` field

- integration-test/pipeline/rest-integration.js
Because
- The original test case for integration failed due to:
1. Removal of the connector-definition endpoint
2. Changes in OAuth scope
This commit:
- Fixes the test cases for integrations
Note:
- Investigate why the test did not raise an error in CI.
> test(integration): fix test cases for integrations

- pkg/recipe/dag.go
- pkg/service/pipeline.go
Because
- Variables might sometimes be optional to provide flexibility. We want pipeline variables to support optional values.
This commit
- Enables optional values for variables.
> feat(trigger): enable optional values for variables

- pkg/component/base/component.go
- pkg/component/base/execution.go
- pkg/data/struct.go
- pkg/data/struct_test.go
- pkg/worker/io.go
- pkg/worker/workflow.go
Because
- the current component initialisation with JSON Schema misses key features
This commit
- add compositional struct support
- support default value injection
- add support for JSON Schema `allOf` for multiple `$ref` used in an object (flattened into the object properties)
```
{
"type": "object",
"allOf": [
{ "$ref": "#/definitions/address" },
{ "$ref": "#/definitions/person" }
],
"properties": {
"customField": { "type": "string" }
},
"required": ["customField"]
}
```
> feat(component,data,base): enhance component features

- pkg/memory/memory.go
- pkg/worker/io.go
- pkg/worker/workflow.go
Because
- We want to preserve the original template for the input and setup sections in the recipe.
This commit
- Separates the template from the rendered values for input and setup.
> feat(recipe): separate the template and the rendered value for input and setup

- go.mod
- go.sum
- integration-test/proto/vdp/pipeline/v1beta/component_definition.proto
- integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
- pkg/component/internal/mock/app_public_service_server_mock.gen.go
- pkg/service/pipeline.go
- pkg/worker/workflow.go
Because
- When a pipeline recipe references a connection, that connection ID will
be fetched from the requester's namespace.
- This forces requesters to create connections in order to trigger
pipelines from other namesapces.
This commit
- Adds a `connectionReferences` field in the pipeline trigger data, which
allows clients to override the references in the recipe with per-batch
references.
- Adds a private endpoint to fetch connections by UID, needed in the
1-minute to impact project.
> feat(trigger): accept connection references in the pipeline trigger data

- go.mod
- go.sum
- integration-test/proto/vdp/pipeline/v1beta/integration.proto
- pkg/component/internal/mock/artifact_public_service_client_mock.gen.go
- pkg/component/internal/mock/artifact_public_service_server_mock.gen.go
- pkg/handler/integration.go
- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/repository/repository_test.go
- pkg/service/integration.go
- pkg/service/main.go
- pkg/service/pipelinerun_test.go
- pkg/service/utils.go
Because
- Agent configurations will store the UIDs of the connections needed to use
in agent tools (UIDs are used to avoid breaking the config if the ID is
updated by the namespace).
This commit
- Adds a private endpoint to fetch a connection by UID.
Part of INS-6933, branch name is wrong.
> feat(connection): add lookup connection endpoint

- .pre-commit-config.yaml
- pkg/component/application/leadiq/v0/io.go
- pkg/component/application/leadiq/v0/task_find_prospects.go
- pkg/component/application/smartlead/v0/README.mdx
- pkg/component/application/smartlead/v0/config/tasks.json
- pkg/component/application/smartlead/v0/io.go
- pkg/component/application/smartlead/v0/task_add_leads.go
- pkg/component/application/smartlead/v0/task_get_sequences.go
- pkg/component/application/smartlead/v0/task_save_sequences.go
- pkg/component/application/smartlead/v0/task_setup_campaign.go
- pkg/component/data/googlesheets/v0/README.mdx
- pkg/component/generic/collection/v0/README.mdx
Because
- we want some fields to be optional
This commit
- support optional fields for smartlead and leadiq
> fix(leadiq, smartlead): change field to optional

- pkg/component/ai/anthropic/v0/io.go
- pkg/component/ai/mistralai/v0/io.go
- pkg/component/ai/openai/v0/io.go
- pkg/component/ai/perplexityai/v0/io.go
- pkg/component/application/github/v0/io.go
- pkg/component/application/leadiq/v0/io.go
- pkg/component/data/googlesheets/v0/config/tasks.json
- pkg/component/data/googlesheets/v0/io.go
- pkg/component/generic/collection/v0/io.go
- pkg/component/operator/audio/v0/io.go
- pkg/component/operator/document/v0/io.go
- pkg/data/struct.go
- pkg/data/struct_test.go
- pkg/worker/io.go
- pkg/worker/workflow.go
Because
- Users may not always provide required data, we can set default values for certain fields when not provided.
This commit
- Adds support for default values in the instill Go tag.
Note
- The current tag requires manual maintenance. In the future, io.go will be auto-generated by compogen based on the tasks.json file, and default values will also be auto-generated.
> feat(data): add support for default value in `instill` Go tag

- pkg/service/main.go
- pkg/service/pipeline.go
Because
- The old webhook-related code is deprecated.
This commit
- removes the unused code.
> chore(service): remove the unused code

- pkg/mock/repository_mock.gen.go
- pkg/repository/repository.go
- pkg/service/pipeline.go
- pkg/service/pipeline_test.go
Because
- A pipeline with the run-on-event setting may be triggered multiple times.
This commit
- Ensures that if no releases exist, the unversioned pipeline’s run-on-event is triggered.
- Ensures that if releases exist, the latest version’s run-on-event is triggered.
> feat(service): trigger latest release version for pipeline with run-on-event setting

- config/config.go
- pkg/repository/repository.go
Because
- we want to hide google drive in cloud before we get drive.readonly scope from Google
This commit
- hide google drive in cloud version
> feat(vdp): skip google drive for cloud version

- pkg/datamodel/datamodel.go
- pkg/service/pipeline.go
Because
- we want users to explicitly define which variables are required.
This commit
- adds support for the required attribute in variables.
> feat(recipe): support `required` attribute for variable

- pkg/component/ai/openai/v0/main.go
Because
- the system message could not be used alongside the chat history.
This commit
- enables the use of system messages with chat history.
> fix(component,openai): enable the use of system messages with chat history

- pkg/component/generic/collection/v0/README.mdx
- pkg/component/generic/collection/v0/config/tasks.json
Because
- all fields in the component schema require a `type`. Currently, we can use `*` as a temporary type. In the future, `type` will be retired, and only `format` will remain.
This commit
- fixes the component schema to comply with the current requirements.
> chore(component,collection): fix component schema

- pkg/component/application/github/v0/config/definition.json
- pkg/component/application/github/v0/config/events.json
- pkg/component/application/slack/v0/config/definition.json
- pkg/component/application/slack/v0/config/events.json
- pkg/component/base/component.go
- pkg/component/generic/schedule/v0/config/definition.json
- pkg/component/generic/schedule/v0/config/events.json
Because
- we have an event card data structure in our component definition response, but it hasn’t been implemented yet.
This commit
- implements event cards in the component definition.
> chore(component): add event cards in component definition

- pkg/worker/workflow.go
This commit
- fixes wrong component id in SchedulePipelineWorkflow
> fix(workflow): fix wrong component id in SchedulePipelineWorkflow

- pkg/component/generic/collection/v0/README.mdx
- pkg/component/tools/compogen/cmd/testdata/readme-component1.txt
- pkg/component/tools/compogen/pkg/gen/readme.go
Because
- `*` is not clear
This commit
- replace `array[*]` with `array[any]`
> feat(compogen): replace array[*] to array[any]

- pkg/repository/repository.go
Because
- we need to filter the integration table based on the edition.
This commit
- fixes the edition filter.
- removes the filter for instill-app component as it has been already removed.
> fix(repository): fix edition filter

- pkg/component/data/pinecone/v0/README.mdx
- pkg/component/data/pinecone/v0/config/definition.json
- pkg/component/data/pinecone/v0/config/setup.json
- pkg/component/data/pinecone/v0/config/tasks.json
- pkg/component/data/pinecone/v0/main.go
- pkg/component/data/pinecone/v0/structs.go
Because
- Rerank API is introduced from Pinecone
- Resolves instill-ai/instill-core#1114
This commit
- Added Pinecone Rerank Support. 
- Inputs: Documents and Query input. We can restrict output to n documents by setting optional field (top-n)
- Output: Reranked Documents and Scores
- Made URL in Pinecone Setup Optional as for rerank input URL is not required. For others, this will still need to be input.
> feat(pinecone): Add rerank task for Pinecone component

- go.mod
- go.sum
- pkg/component/data/pinecone/v0/README.mdx
- pkg/component/data/pinecone/v0/component_test.go
- pkg/component/data/pinecone/v0/config/definition.json
- pkg/component/data/pinecone/v0/config/tasks.json
- pkg/component/data/pinecone/v0/io.go
- pkg/component/data/pinecone/v0/main.go
- pkg/component/data/pinecone/v0/structs.go
- pkg/component/data/pinecone/v0/task_batch_upsert.go
- pkg/component/data/pinecone/v0/task_query.go
- pkg/component/data/pinecone/v0/task_rerank.go
- pkg/component/data/pinecone/v0/task_upsert.go
Because
- we will need batch upsert
This commit
- refactor task upsert with concurrent execution
> feat(pinecone): pinecone batch upsert

- cmd/main/main.go
- pkg/service/main.go
- pkg/service/pipeline_test.go
- pkg/service/pipelinerun_test.go
Because
- Using parameter structs for injecting dependencies is dangerous, especially when constructors are consumed by other packages / repos. Explicit parameters produce compilation errors when new dependencies are added and the client package doesn't update the constructor method call.
This commit
- Transforms `service.NewService` to a constructor method with one argument per dependency.
> chore(service): remove parametrized service constructor

- pkg/service/pipeline.go
This commit
- resolves issue where default value for number cannot be an integer
Note
- This is a temporary solution. We will improve the conversion between JSON and Instill Format to make the implementation clearer.
> fix(trigger): resolve issue where default value for number cannot be an integer

- pkg/memory/memory.go
- pkg/recipe/dag.go
Because
- The console requires component intermediate data for display.
This commit
- Adds component intermediate data to the trigger stream/response.
Note
- The old implementation has been restored in this commit. For binary data, we need to return its blob URL instead of base64 data in the future.
> fix(trigger): add component intermediate data in the trigger stream/response

- cmd/migration/main.go
- config/config.yaml
- go.mod
- go.sum
- pkg/component/internal/mock/artifact_public_service_client_mock.gen.go
- pkg/component/internal/mock/artifact_public_service_server_mock.gen.go
- pkg/datamodel/runlogging.go
- pkg/db/migration/000039_add_pipeline_run_expiration_time.down.sql
- pkg/db/migration/000039_add_pipeline_run_expiration_time.up.sql
- pkg/db/migration/convert/convert000039/convert.go
- pkg/db/migration/migration.go
- pkg/service/pipelinerun.go
- pkg/service/utils.go
- pkg/worker/minioactivity.go
- pkg/worker/workflow.go
Because
- When the blob data associated to a pipeline / component run expires, the backend will stop serving it. It will be useful to both backend and clients to know that the data isn't there because it expired (instead of because an error occurred).
This commit
- Adds a field with the blob data expiration data to the run entities.
> feat(pipeline): add blob expiration time to run logs

- go.mod
- go.sum
Because
- A new package of `x` has been released.
This commit
- Update `x` module to v0.6.0.
> chore(x): update x package with release

- pkg/component/data/googledrive/v0/.compogen/intro.mdx
- pkg/component/data/googledrive/v0/README.mdx
- pkg/component/data/googledrive/v0/main.go
Because
- When building the `instill.tech` docs, Google Drive was [included](https://github.com/instill-ai/instill.tech/pull/1279#discussion_r1886644507).
- This is correct because CE versions can use this component (i.e. we shouldn't hide the doc), but might generate confusion for Cloud users.
This commit
- Specifies CE-only usage in `google-drive` component document.
> chore(google-drive): document component is only available on CE

- pkg/worker/io.go
- pkg/worker/workflow.go
Because
- Originally, users could not see the error message from a component within an iterator.
This commit
- return the error message from a component inside an iterator.
> feat(pipeline): return the error from a component inside an iterator

- .github/workflows/integration-test.yml
- pkg/component/ai/perplexity/v0/.compogen/bottom.mdx
- pkg/component/ai/perplexity/v0/README.mdx
- pkg/component/ai/perplexity/v0/config/tasks.yaml
Because
- New Sonar models have been published by Perplexity AI.
This commit
- Updates the Perplexity component with these models.
> feat(perplexity): add new Sonar models

- Dockerfile
- Dockerfile.dev
Because
- Image build succeeded on the PR CI but fails on the `main` branch workflow.
This commit
- Splits the errored command to gather more information
- Adds some minor corrections to the Dockerfile
> fix(ci): registry image build

- Dockerfile
- Dockerfile.dev
- Makefile
Because
- `pip install docling` will compile dependencies (e.g., shapely) for `aarch64` platform, which requires further development libraries
This commit
- remove `GOLANG_VERSION` in Makefile `build-dev` and `build-latest` target as we now hardcode Go version in Dockerfile
- add the missing dependent packages:
- build-essential
- python3-dev
- libgeos++-dev
> ci(docker): fix Dockerifle building docling

- .github/workflows/coverage.yml
- .github/workflows/integration-test.yml
- Dockerfile
- Dockerfile.dev
- Makefile
- pkg/component/operator/document/v0/config/tasks.yaml
- pkg/component/operator/document/v0/convert_document_to_markdown.go
- pkg/component/operator/document/v0/convert_document_to_markdown_test.go
- pkg/component/operator/document/v0/io.go
- pkg/component/operator/document/v0/transformer/execution/docling_pdf_to_md_converter.py
- pkg/component/operator/document/v0/transformer/markdown.go
- pkg/component/operator/document/v0/transformer/markdowntransformer.go
- pkg/component/operator/document/v0/transformer/pdftomarkdown.go
- pkg/data/document.go
Because
- Some EasyOCR models are needed by Docling to transform PDF to Markdown.  Without them, the first execution of the document component fails because the output starts by a "Downloading detection model, please wait..." print.
- This also prevented coverage for the Docling converter.
- The `use-docling` parameter in the document operator is less open to changes that an enum `converter` selector.
This commit
- Adds the EasyOCR models to the Docker images.
- Corrects the integration test in the CI after [the latest changes in instill-core
](https://github.com/instill-ai/instill-core/pull/1172).
- Replaces the `use-docling` parameter by `converter`.
The following changes are made on the `Dockerfile`:
- `nobody:nogroup` needs to have a $HOME where the EasyOCR models will be placed …
> feat(Docling): prefetch model artifacts

- .github/workflows/images.yml
Because
- Originally, we used QEMU for cross-compiling images, but it was slow and unstable.
This commit
- Uses an ARM runner to speed up the image build process.
> ci(github): use ARM runner to speed up the image build process

- pkg/component/ai/ollama/v0/.compogen/setup-hosting.mdx
- pkg/component/ai/ollama/v0/README.mdx
This commit
- renames `vdp` to `pipeline` in doc.
> chore(ollama): rename vdp to pipeline in doc

- .github/workflows/images.yml
- .github/workflows/integration-test.yml
- Dockerfile
- cmd/main/main.go
- go.mod
- go.sum
Because
- We want to identify the service that is performing a MinIO action.
This commit
- Adds client information (app name and version) to the MinIO requests according to instill-ai/x/pull/37.
> feat(minio): add service name and version to MinIO requests

- cmd/main/main.go
- go.mod
- go.sum
- pkg/external/external.go
- pkg/service/main.go
- pkg/service/pipeline.go
- pkg/service/pipeline_test.go
- pkg/worker/main.go
Because
- The artifact binary fetcher interacted with MinIO without providing the app and user information that we need for the audit logs.
This commit
- Uses the latest version of `x/minio` to provide such information.
> feat(minio): add client info and user header to artifact binary fetcher

- .github/workflows/coverage.yml
- Dockerfile
- pkg/component/internal/mock/agent_public_service_server_mock.gen.go
Because
- Coverage action is failing due to insufficient disk space.
This commit
- Optimizes disk usage in coverage action.
> fix(ci): optimize disk usage in coverage worklfow

- .github/workflows/coverage.yml
- Dockerfile
- cmd/main/main.go
- go.mod
- go.sum
- pkg/component/internal/mock/agent_public_service_server_mock.gen.go
- pkg/handler/triggerhandler.go
- pkg/memory/memory.go
- pkg/memory/pubsub.go
- pkg/middleware/middleware.go
- pkg/pubsub/pubsub.go
- pkg/pubsub/redis.go
- pkg/service/pipeline.go
- pkg/service/pipeline_test.go
- pkg/worker/workflow.go
Because
- On streamed pipeline triggers, the workers communicate with the API via in-process memory.
- This prevents us from separating the `main` and `worker` processes for more efficient scaling.
This commit
- Replaces the in-process memory communication by a Publication / Subscription pattern over Redis.
> feat(streaming): use Redis pub/sub to stream pipeline triggers

- cmd/main/main.go
- pkg/memory/memory.go
- pkg/recipe/dag.go
- pkg/service/pipeline.go
- pkg/service/webhook.go
- pkg/worker/io.go
- pkg/worker/main.go
- pkg/worker/minioactivity.go
- pkg/worker/workflow.go
Because
- The pipeline information that's loaded as in-process memory during trigger execution prevents us from scaling workers independently.
This commit
- Removes the pipeline recipe snapshot from the in-process memory. Recipes shouldn't be larger than the Temporal history constraints.
- This is achieved by passing the recipe as a parameter to the trigger workflow. This parameter is propagated to the activities that consume this information, so they don't need to fetch the recipe from the workflow memory anymore.
> feat(memory): remove recipe from in-process memory

- cmd/main/main.go
- go.mod
- go.sum
- pkg/data/audio.go
- pkg/data/encode.go
- pkg/data/encode_test.go
- pkg/data/file.go
- pkg/data/image.go
- pkg/data/video.go
- pkg/memory/memory.go
- pkg/memory/store.go
- pkg/memory/workflow.go
- pkg/recipe/dag.go
- pkg/service/convert.go
- pkg/service/main.go
- pkg/service/metadataretention.go
- pkg/service/pipeline.go
- pkg/service/pipeline_test.go
- pkg/service/webhook.go
- pkg/worker/io.go
- pkg/worker/main.go
- pkg/worker/workflow.go
Because
- We're communicating the workflow memory information between the temporal clients and workers through an in-memory structure.
- This forces us to run the worker in the same process as the client.
This commit
- Stores and reads the workflow memory as a MinIO blob to decouple client and worker.
> feat(trigger): use MinIO to store workflow memory

- pkg/external/external.go
Because
- The worker needs to make requests to the pipeline server, but this process might be run in a separate container.
This commit
- Uses the server's instance ID in the configuration to connect to the pipeline server.
> fix(worker): use pipeline server host in pipeline client

- pkg/component/base/migrate.go
- pkg/component/base/testdata/wantComponentDefinition.yaml
- pkg/component/base/testdata/wantOperatorDefinition.yaml
Because:
- Console still needs instillFormat to render the data UI.
This commit:
- Makes the component definition response compatible with Console.
> fix(component): make component definition response compatiable with Console

- pkg/memory/store.go
- pkg/memory/workflow.go
- pkg/worker/io.go
Because
- Streamed executions with iterators failed because the `_output` key
wasn't set in the iterator's child workflow memory. This is
initialized on `InitComponentsActivity`, which is run only on parent
workflows.
This commit
- Intializes this field on workflow memory creation. `ComponentActivity`
will use it to update the (child) pipeline output at the end of the
sub-component execution.
> fix(iterator): always initialize pipeline output template

- pkg/component/data/instillartifact/v0/task_get_chunks_metadata.go
- pkg/component/data/instillartifact/v0/task_get_file_in_markdown.go
- pkg/component/data/instillartifact/v0/task_get_files_metadata.go
- pkg/component/data/instillartifact/v0/task_match_files_status.go
- pkg/component/data/instillartifact/v0/task_query.go
- pkg/component/data/instillartifact/v0/task_search_chunks.go
- pkg/component/data/instillartifact/v0/task_sync_files.go
- pkg/component/data/instillartifact/v0/task_upload_files.go
Because
- connection is close before execution completed.
This commit
- remove duplicated connection close.
> fix(component,artifact): remove duplicated connection close

- .github/workflows/integration-test.yml
- integration-test/pipeline/grpc-pipeline-private.js
- integration-test/pipeline/grpc-pipeline-public-with-jwt.js
- integration-test/pipeline/grpc-pipeline-public.js
- integration-test/pipeline/grpc-trigger-async.js
- integration-test/pipeline/grpc-trigger.js
- integration-test/pipeline/grpc.js
- integration-test/pipeline/rest-pipeline-private.js
- integration-test/pipeline/rest-pipeline-public-with-jwt.js
- integration-test/pipeline/rest-pipeline-public.js
- integration-test/pipeline/rest-trigger-async.js
- integration-test/pipeline/rest-trigger.js
- integration-test/pipeline/rest.js
- pkg/handler/pipeline.go
- pkg/service/pipeline.go
- pkg/worker/workflow.go
Because
- When a component failed to execute, the pipeline status was FAILED but
the component status wasn't
This commit
- Sets the error correctly in the component activity so the deferred
cleanup function that updates the component run can capture the
execution status.
> fix(component-run): set component status when execution failed

- go.mod
- go.sum
- pkg/acl/acl.go
- pkg/constant/constant.go
- pkg/external/external.go
- pkg/handler/pipeline.go
- pkg/handler/utils.go
- pkg/logger/otel/const.go
- pkg/recipe/variable.go
- pkg/repository/repository.go
- pkg/resource/resource.go
- pkg/service/convert.go
- pkg/service/integration.go
- pkg/service/pipeline.go
- pkg/service/pipelinerun.go
- pkg/service/pipelinerun_test.go
- pkg/service/utils.go
- pkg/worker/minioactivity.go
This commit
- Uses the latest `instill-ai/x/temporal` to propagate the gRPC metadata
in requests to the Temporal workflows and activities.
> feat(temporal): propagate request metadata to Temporal headers

- pkg/worker/workflow.go
Because
- errors arise when creating Temporal session.
This commit
- catches and prints the error when creating Temporal session failed for further analysis
> fix(worker): catch the error when creating Temporal session failed

- pkg/component/ai/openai/v0/main.go
- pkg/component/ai/openai/v0/preprocess.go
- pkg/component/ai/openai/v0/preprocess_test.go
Because
- OpenAI downsizes images before processing them, there’s no need to send large images.
This commit
- Resizes the image before sending it to OpenAI.
> fix(component,openai): resize the image before sending to OpenAI

- .github/workflows/images.yml
Because
- git tag contains `-rc` suffix already.
This commit
- removed the redundant `-rc` suffix and combine the `rc` and `release` step.
> ci(workflows): fix rc image tag

- pkg/component/operator/document/v0/transformer/markdowntransformer.go
Because
- the stderr pipe output pollute the output parsing
This commit
- fix the wrong python script output parsing
> fix(component,document): fix the wrong python script output parsing

- pkg/component/operator/document/v0/transformer/execution/docling_pdf_to_md_converter.py
- pkg/component/operator/document/v0/transformer/execution/pdfplumber_pdf_to_md_converter.py
- pkg/component/operator/document/v0/transformer/markdowntransformer.go
Because
- `pdfplumber` when converting certain files
- `docling` printed unstructured information to `stderr` outside of the logging system
This commit
- Makes `pdfplumber` silently fail so other components can continue the execution
- Improves the python scripts to capture all the `stderr` information.
> fix(document): make Python scripts fail silently on document-to-markdown conversion

- pkg/component/generic/http/v0/README.mdx
- pkg/component/generic/http/v0/component_test.go
- pkg/component/generic/http/v0/config/tasks.yaml
- pkg/component/generic/http/v0/main.go
Because
- The internal network of an Instill Core deployment is exposed through
the `http` component.
This commit
- Blocks the endpoints resolved to internal IP ranges.
- Reworks coverage of the component to use an external URL for testing.
> chore(http): block internal endpoints in HTTP component.

- .github/workflows/coverage.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/images.yml
- .github/workflows/integration-test.yml
- Dockerfile
- Makefile
- cmd/main/main.go
- cmd/worker/main.go
- config/config.go
- config/config.yaml
- pkg/usage/usage.go
Because
- the service version for the repo commit head at the moment is tagged using the long commit hash. We'd like to keep it short. 
This commit
- update the build-time versioning logic.
> ci(workflows): adopt short commit hash for service version

- .github/CONTRIBUTING.md
- .github/workflows/integration-test.yml
- go.mod
- go.sum
Because
- usage-client has a a new version to adopt the latest services
This commit
- bumps up the usage-client version
- updates contributing guidline
> chore(dep): bump up usage-client version

- cmd/migration/main.go
- config/config.go
- config/config.yaml
- go.mod
- go.sum
- pkg/component/data/instillartifact/v0/config/definition.yaml
- pkg/component/data/instillartifact/v0/config/tasks.yaml
- pkg/component/data/instillartifact/v0/io.go
- pkg/component/data/instillartifact/v0/task_query.go
- pkg/component/data/instillartifact/v0/task_search_chunks.go
- pkg/db/db.go
Because
- Filename isn't a unique identifier in catalogs anymore
This commit
- Adds a file UID param in the retrieval task in the Instill Artifact component.
- The filename param is kept temporarily for backwards compatibility while clients update their recipes.
- Adds a file UID field in the retrieved chunk object.
- Removes the database schema version from the config.
> feat(artifact): add file UID param in retrieval task

- pkg/external/external.go
Because
- base64.StdEncoding might generate `/` in the Base64 string, which can break the structure of the generated blob URL.
This commit:
- Uses base64.URLEncoding to decode the blob URL.
> fix(external): use URLEncoding to decode blob URL

- cmd/init/main.go
- cmd/worker/main.go
Because
- the Temporal namespace needs to be created before both `cmd/main` and `cmd/worker`.
This commit
- moves Temporal namespace creation to cmd/init
> fix(cmd): move Temporal namespace creation to cmd/init

- pkg/component/data/instillartifact/v0/client.go
- pkg/component/internal/util/helper.go
- pkg/recipe/variable.go
- pkg/service/pipeline.go
Because
- We need to propagate headers with the `instill-` prefix to the instill-artifact component.
This commit
- Fixes missing propagation of original request header instill-artifact component
> fix(component): fix missing propagation of original request header instill-artifact component

- cmd/init/main.go
- config/config.yaml
- go.mod
- go.sum
Because
- The Temporal namespace will now be initialized when the Temporal service starts.
Ref: https://github.com/instill-ai/instill-core/pull/1352
- We now use the shared `instill-core` namespace across all services.
This commit
- Removes Temporal namespace initialization
- Adopts the latest `x/temporal` package to support API key authentication for connecting to Temporal Cloud
> feat(temporal): remove Temporal namespace initialization

- pkg/datamodel/runlogging.go
- pkg/db/migration/000041_drop_total_duration.down.sql
- pkg/db/migration/000041_drop_total_duration.up.sql
- pkg/db/migration/migration.go
- pkg/repository/repository_test.go
- pkg/service/pipeline.go
- pkg/service/pipelinerun.go
- pkg/service/pipelinerun_test.go
- pkg/service/utils.go
- pkg/service/webhook.go
- pkg/worker/workflow.go
Because
- The total duration of a pipeline / component run was set only on
failed states.
- Total duration is redundant with started / completed timestamps, which
are always set.
This commit
- Removes the total duration column in the database
- Computes the total duration in the API as the time diff between the
completed and started timestamps
> fix(run): return correct total duration

- pkg/service/pipelinerun.go
- pkg/service/pipelinerun_test.go
- pkg/service/utils.go
Because
- The permission check for private data is wrong.
This commit
- Adjusts the permission check for 
- Fixes wrong time unit for component logs
> fix(log): fix permission check for run logs

- pkg/component/ai/gemini/v0/io.go
- pkg/component/ai/gemini/v0/task_chat.go
- pkg/component/ai/gemini/v0/task_chat_test.go
This commit
- optimize the IO struct by using the data.Image interface for unmarshaling.
> chore(component,gemini): optimize the IO struct

- pkg/component/ai/instillmodel/v0/main_test.go
- pkg/component/base/executionwrapper.go
- pkg/component/base/executionwrapper_test.go
- pkg/component/internal/util/helper.go
- pkg/worker/io.go
Because
- Usage handler error produces a misleading error when the input data
fails to be rendered.
This commit
- Fixes INS-8583
- Passes only the valid inputs to the usage checker.
- Returns a fatal error if no valid inputs could be rendered.
> fix(usage): treat input rendering error as fatal

- pkg/component/ai/gemini/v0/task_chat.go
Because
- The previous implementation extracted text content using `doc.Text()` for text-based documents but Gemini actually supports plain text, making `doc.Text()` unnecessary.
This commit
- Updates text-based document processing to use base64 encoding like PDFs for consistent handling
- Removes the `doc.Text()` extraction step that could cause processing failures
- Ensures both PDFs and text-based documents (TXT, Markdown, HTML, XML, etc.) are handled uniformly by passing base64 data directly to the Gemini API
- Maintains proper MIME type detection by using the actual `contentType` instead of hardcoded values
> fix(component,ai,gemini): correct text-based documents logic

- pkg/component/base/execution.go
- pkg/data/struct.go
- pkg/data/struct_test.go
- pkg/worker/io.go
Because
- External packages like `genai` use camelCase json tags while Instill's schema uses kebab-case, causing unmarshaling incompatibility
- **Nested Go struct fields using different naming conventions can cause silent data loss** - when top-level structs use `instill` tags but nested external types use `json` tags with different conventions, field mappings fail and data is silently dropped
- Manual specification of naming conventions creates confusion and maintenance overhead for users
- Repeated field name resolution operations impact performance in high-throughput scenarios
- Code duplication existed between marshaling and unmarshaling logic for handling different naming conventions
This commit
- Implements automatic naming convention detection that tries multiple formats …
> perf(data): implement automatic field naming convention detection with LRU caching

- Dockerfile
- Dockerfile.dev
Because
- The existing Dockerfiles had inefficient layer caching and sequential operations
- Build times were slow due to poor separation of dependencies and application code
- External downloads and package installations were not optimized for Docker's layer caching mechanism
- The production and development builds lacked proper multi-stage optimization
This commit
- Implements advanced multi-stage builds for both `Dockerfile` and `Dockerfile.dev`
- Separates build dependencies, binary dependencies, and runtime dependencies into distinct stages
- Optimizes Go build cache mounts to preserve build artifacts between builds
- Combines package installations into single layers to reduce image size
- Reorganizes external downloads (FFmpeg, ONNX Runtime, EasyOCR models) for better caching
- …
> ci(docker): optimize Dockerfiles with multi-stage builds for faster build times

- pkg/component/operator/video/v0/helper_test.go
- pkg/component/operator/video/v0/task_embed_audio_test.go
- pkg/component/operator/video/v0/task_extract_audio_test.go
- pkg/component/operator/video/v0/task_extract_frames_test.go
- pkg/component/operator/video/v0/task_segment_test.go
- pkg/component/operator/video/v0/task_subsample_test.go
Because**
- Video package unit tests were taking > 700 seconds to complete, significantly slowing down the development feedback loop
- FFmpeg operations were using full resolution processing unnecessarily for test validation
- Test cases were running sequentially instead of leveraging parallel execution
- Redundant file I/O operations were occurring for the same test data files
- Frame and pixel comparisons were processing every single data point when sampling would suffice for validation
This commit
- Adds `c.Parallel()` to all video test cases enabling concurrent test execution
- Optimizes FFmpeg frame extraction with reduced resolution (160x120) and faster encoding settings (`q:v=8`)
- Implements smart frame comparison that samples key frames (first, quarter, middle, three-quarter, …
> perf(component,operator,video): optimize unit test performance by 59.7%

- pkg/data/struct.go
- pkg/data/struct_test.go
Because
- The data unmarshaling framework lacked native support for `time.Duration` and `time.Time` types, requiring manual string conversion in application code
- There was no pattern validation capability to enforce schema constraints during unmarshaling, leading to inconsistent data validation
- JSON number inputs could bypass intended string-only validation for duration fields, causing unexpected behavior
- Time types could not be marshaled back to consistent, API-compatible string formats
- The struct.go file contained significant code duplication that reduced maintainability
**This commit**
- **Implements native `time.Duration` and `time.Time` unmarshaling**: Automatically converts string values to Go time types with support for multiple parsing strategies including RFC3339, Go …
> feat(data): implement time types support with pattern validation

- pkg/usage/usage.go
Because
- The `TriggerSingleReporter` method was missing the same error filtering logic that exists in `NewUsage` and `StartReporter` methods
- When `GetUserAdmin` fails with "users/admin" error, it should be treated as a debug message rather than an error since only Instill Core CE has the default "admin" user
- Without this filtering, false alarm errors were being logged when the admin user doesn't exist in other Instill editions
This commit
- Adds the same error filtering pattern to `TriggerSingleReporter` that already exists in `NewUsage` and `StartReporter`
- Changes the error handling to check if the error contains "users/admin" and treats it as a debug log instead of an error log
- Ensures consistent error handling across all three methods when dealing with the default admin user …
> fix(usage): add missing error filtering for users/admin

- pkg/component/ai/gemini/v0/config/tasks.yaml
- pkg/component/ai/gemini/v0/io.go
- pkg/component/ai/gemini/v0/task_chat.go
- pkg/component/ai/gemini/v0/task_chat_test.go
Because
- We have the unified `usage` field for `TASK_CHAT` in different AI components
- The Gemini component had redundant `usage` and `usage-metadata` fields that provided overlapping token usage information
- The `usage` field was a simple object while `usage-metadata` contained detailed structured information
This commit
- Merges the `usage` and `usage-metadata` fields into a single comprehensive `usage` field
- Updates the YAML schema to reference the detailed `usage-metadata` definition for the `usage` field
- Removes the separate `usage-metadata` field from the output schema and Go structs
- Updates all related code to populate and access usage information through the unified `usage` field
- Maintains backward compatibility by preserving all detailed token usage statistics (prompt …
> refactor(component,ai,gemini): merge usage and usage-metadata fields into single usage field

- pkg/component/ai/gemini/v0/.compogen/bottom.mdx
- pkg/component/ai/gemini/v0/README.mdx
- pkg/component/ai/gemini/v0/config/definition.yaml
- pkg/component/ai/gemini/v0/config/tasks.yaml
- pkg/component/ai/gemini/v0/io.go
- pkg/component/ai/gemini/v0/main.go
- pkg/component/ai/gemini/v0/task_text_embeddings.go
- pkg/component/ai/gemini/v0/task_text_embeddings_test.go
- pkg/component/operator/image/v0/config/schema.yaml
Because
- The Gemini component needed support for text embeddings functionality to enable use cases like semantic search, classification, and clustering
- Users required the ability to generate embeddings using the `gemini-embedding-001` model with various task types for optimal performance
This commit
- Adds `TASK_TEXT_EMBEDDINGS` task with comprehensive input/output schema supporting multiple task types 
- Implements TaskTextEmbeddingsInput and TaskTextEmbeddingsOutput structs with proper validation and embedding generation
- Adds comprehensive test coverage for the text embeddings functionality
> feat(component,ai,gemini): add text embeddings task support

- pkg/data/file.go
- Generated filenames had double dots (e.g., `uuid..flac` instead of `uuid.flac`)
- The `mimetype.Detect(b).Extension()` method already returns file extensions with a leading dot
- The format string `"%s.%s"` was adding an extra dot before the extension
- Fixes the filename generation in `NewFileFromBytes` function by removing the extra dot from the format string
- Changes `fmt.Sprintf("%s.%s", fileUID, extension)` to `fmt.Sprintf("%s%s", fileUID, extension)`
- Ensures generated filenames have correct format like `uuid.flac` instead of `uuid..flac`
> fix(data): remove duplicate dot in generated filenames
