instill-ai/pipeline-backend

openapis/pipeline.swagger.json

Because
- ReDoc need a public URL to create a document page
This commit
- add a swagger file for testing purpose

docs: add swagger file for testing purpose

---

go.mod
go.sum
rpc/marshal.go
rpc/unmarshal.go

Because
- some definitions that are not used
This commit
- remove unused code

fix: remove unused code

---

pkg/repository/pipeline.go
pkg/service/pipeline.go
rpc/pipeline.go

Because
- found issues during integration test with vdp and need to be fixed
This commit
- correct codes during integration test

fix: correct codes during integration test

---

pkg/service/pipeline.go
rpc/pipeline.go

Because
- we need a public struct for reusing purpose
This commit
- change struct definition from private to public

fix: change struct definition from private to public

---

.github/workflows/add-issue-to-prj.yml
README.md

Because
- we are continuously improving the documentation
This commit
- update README.md

docs: update README.md

---

configs/models/pipeline.json

Because
- JSON schema definition has duplicated field
This commit
- Remove duplicated field

refactor: remove duplicated definition

---

go.mod
go.sum
pkg/service/convert.go

Because
- support instance segmentation task
This commit
- add instance segmentation task output

chore: support instance segmentation task

---

integration-test/rest-trigger-async.js
integration-test/rest-trigger-sync.js
pkg/service/service_test.go

Because
- the sample image URL for testing is out of date
This commit
- update sample image URL for testing

test: update sample image url

---

integration-test/rest-trigger-async.js
integration-test/rest-trigger-sync.js

Because
- error when creating file in format
This commit
- fix creating file in integration test formdata

chore: update formdata file in integration test

---

.pre-commit-config.yaml
config/config.yaml
go.sum
pkg/service/service.go
pkg/usage/usage.go

Because
- CORS configuration is set in docker-compose files
- triggering usage metric is not for only image
This commit
- remove cors default config
- rename usage metric
- upgrade pre-commit hooks

chore: change config and usage metric

---

go.mod
go.sum
integration-test/rest.js
pkg/service/convert.go
pkg/service/mock_model_grpc_test.go

Because
- model-backend deploy/undeploy a model instance asynchronous
This commit
- update integration test when deploying a model instance

chore: update model backend

---

Dockerfile.dev
integration-test/const.js

Because
- run test with API gateway
This commit
- change the server port to API gateway port

chore: update integration test

---

go.mod
go.sum
internal/constant/constant.go
pkg/handler/handler.go
pkg/handler/handlercustom.go
pkg/handler/payload.go
pkg/service/service.go

Because
- VDP supported text to image and text generation tasks
This commit
- support trigger those 2 tasks from the pipeline-backend

feat: add new ai task

---

pkg/service/service.go

Because
- failing integration-test with pipeline renaming
This commit
- fix delete/update resource execution order
- fix id/newid

fix(controller): fix rename id and execution order

---

go.mod
go.sum
integration-test/grpc-pipeline-private.js
integration-test/grpc-pipeline-public.js
integration-test/grpc.js
integration-test/helper.js
integration-test/rest-pipeline-private.js
integration-test/rest.js
pkg/handler/privateHandler.go
pkg/handler/publicHandler.go
pkg/service/controller.go
pkg/service/convert.go
pkg/service/mock_connector_private_grpc_test.go
pkg/service/mock_connector_public_grpc_test.go
pkg/service/mock_model_private_grpc_test.go
pkg/service/mock_user_grpc_test.go
pkg/service/service.go
pkg/service/service_test.go
pkg/service/state.go

Because
- allow same resource name under different user namespace
This commit
- adopt controller's removal of resource name and use resource uuid
- remove Get admin api

chore: update controller resource name to uid

---

pkg/logger/logger.go

Because
- log to stdout instead of stderr
This commit
- log to stdout instead of stderr

chore: log to stdout instead of stderr

---

pkg/handler/privateHandler.go
pkg/handler/publicHandler.go
pkg/logger/logger.go
pkg/service/convert.go
pkg/service/mode.go

Because
- Need to show debug log when dev mode
This commit
- Update logger levels

chore: update logger

---

pkg/service/convert.go

Because
- we sure not return 500 when the pipeline recipe is broken due to some unexpectedly behavior (such as model is gone in db). 
This commit
- add a workaround method to handle broken pipeline recipe

chore: add a workaround solution for broken recipe

---

integration-test/grpc-pipeline-public.js
integration-test/rest-pipeline-public.js
pkg/service/mode.go

Because
- we don't allow component id duplicated in the recipe
This commit
- check the duplicated component id
- add format limit for component id

chore: add check for component id

---

pkg/service/mode.go

Because
- let the component id constraint not so strict 
This commit
- update component id constraint

chore: update recipe constraint

---

.github/workflows/integration-test.yml
Makefile
cmd/main/main.go
config/config.go
config/config.yaml
pkg/external/external.go

Because
- retire `ITMODE` and change to `ITMODE_ENABLED` in VDP
This commit
- update `ITMODE` naming
Fixes INS-865

chore(env): update `ITMODE` naming in VDP

---

cmd/main/main.go
pkg/handler/handlercustom.go
pkg/handler/publicHandler.go
pkg/logger/otel/const.go
pkg/logger/otel/metrics.go
pkg/logger/otel/tracing.go
pkg/middleware/misc.go
pkg/utils/utils.go
pkg/worker/workflow.go

Because
- unify log message structure for better readability and `queryability`
This commit
- update log message structure

chore(logger): adopt new logging format

---

pkg/external/external.go

Because
- fix influxdb init
This commit
- fix influxdb init

chore: fix influxdb init

---

go.mod
go.sum
pkg/handler/publicHandler.go
pkg/service/dag.go
pkg/service/mode.go
pkg/service/service.go
pkg/utils/dag.go
pkg/utils/utils.go
pkg/worker/workflow.go

Because
- For DAG pipeline, we use a dependencies field to define the edge of the graph
This commit
- use topological sort to determine the execution order of DAG
- implement DAG for triggering endpoints

chore: implement dependency function in recipe

---

cmd/migration/000002_migrate.go
cmd/migration/000003_migrate.go
cmd/migration/main.go
config/config.yaml

Because
- the original dependencies field in pipeline recipe is always empty.
This commit
- automatically generate recipe dependencies with default value for migration

chore: add recipe dependencies migration

---

pkg/utils/utils.go

Because
- update metric field name
This commit
- update metric field name

chore: update metric field name

---

config/model/pipeline.json
pkg/service/service.go
pkg/utils/dag.go
pkg/worker/workflow.go

Because
- need to allow empty recipe
This commit
- allow empty recipe and update the recipe check function

chore: allow empty recipe

---

cmd/worker/main.go
pkg/service/mode.go
pkg/utils/utils.go
pkg/worker/worker.go
pkg/worker/workflow.go

Because
- We can not have long-running job inside temporal workflow.
- The DAG recipe check function is not robust.
This commit
- Improve DAG recipe check function
- Add a new DownloadActivity for downloading images

chore: fix dag bugs

---

config/config.yaml

Because
- update bucket name
This commit
- update bucket name

chore: update bucket name

---

pkg/service/service.go
pkg/worker/workflow.go

Because
- fix batch download image bug
This commit
- fix batch download image bug

chore: fix batch download image bug

---

integration-test/const.js
integration-test/grpc-pipeline-private.js
integration-test/grpc-pipeline-public-with-jwt.js
integration-test/grpc-pipeline-public.js
integration-test/grpc-trigger-async.js
integration-test/grpc-trigger-sync.js
integration-test/grpc.js
integration-test/helper.js
integration-test/rest-pipeline-private.js
integration-test/rest-pipeline-public-with-jwt.js
integration-test/rest-pipeline-public.js
integration-test/rest-trigger-async.js
integration-test/rest-trigger-sync.js
integration-test/rest.js

Because
- update test cases
- 
This commit
- update test cases

chore: update test cases

---

integration-test/helper.js
pkg/handler/convert.go
pkg/service/service.go

Because
- the includeResourceDetailInRecipe() is not needed in ListPipelinesAdmin()
This commit
- remove includeResourceDetailInRecipe for ListPipelinesAdmin()

chore: remove includeResourceDetailInRecipe for ListPipelinesAdmin()

---

integration-test/grpc-trigger.js
integration-test/grpc.js
integration-test/rest-trigger.js
integration-test/rest.js

Because
- need to add test-cases for pipeline dependency
This commit
- add test-cases for pipeline dependency

chore: add test-cases for pipeline dependency

---

go.mod
go.sum
pkg/service/service.go
pkg/utils/utils.go
pkg/worker/workflow.go

Because
- we are going to support audio unstructured data
This commit
- support audio data in pipeline backend
- refactor util functions for converting between Pipeline DataPayload and Connector DataPayload

chore: support audio data in pipeline backend

---

go.mod
go.sum
pkg/handler/publicHandler.go
pkg/service/influx.go
pkg/service/service.go
pkg/usage/usage.go
pkg/utils/utils.go
pkg/worker/utils.go
pkg/worker/workflow.go

Because
- provide more detailed information in usage collection
This commit
- add usage collection trigger data and update usage data format

chore(usage): update usage collection data format

---

go.mod
go.sum
integration-test/grpc-pipeline-private.js
integration-test/grpc-pipeline-public-with-jwt.js
integration-test/grpc-pipeline-public.js
integration-test/proto/vdp/connector/v1alpha/connector.proto
integration-test/proto/vdp/connector/v1alpha/connector_definition.proto
integration-test/proto/vdp/connector/v1alpha/connector_public_service.proto
integration-test/proto/vdp/pipeline/v1alpha/pipeline.proto
integration-test/proto/vdp/pipeline/v1alpha/pipeline_public_service.proto
integration-test/rest-pipeline-public-with-jwt.js
integration-test/rest-pipeline-public.js
internal/resource/resource.go
pkg/handler/convert.go
pkg/handler/privateHandler.go
pkg/handler/publicHandler.go
pkg/repository/repository.go
pkg/service/convert.go
pkg/service/mock_connector_public_grpc_test.go
pkg/service/mock_repository_test.go
pkg/service/service.go
pkg/utils/utils.go

Because
- the boundary of handler and service is not clear.
This commit
- refactor datamodel and proto conversion

chore: refactor datamodel and proto conversion

---

pkg/service/convert.go

Because
- component type is wrong
This commit
- fix component type bug

chore: fix component type bug

---

pkg/operator/end/config/definitions.json
pkg/operator/end/config/seed/component.json
pkg/operator/start/config/definitions.json
pkg/operator/start/config/seed/component.json
pkg/service/convert.go

Because
- the `delete_time` shouldn't return zero when it is not deleted
This commit
- set `delete_time` null when it is not deleted
- fix operator json-schema bug

chore: set `delete_time` null when it is not deleted

---

pkg/handler/publicHandler.go
pkg/utils/dag.go

Because
- the error msg is not accurate
This commit
- improve error msg

chore: improve error msg

---

pkg/service/openapi.go
pkg/utils/dag.go

Because
- in order to concat data from different components, we should support array in component reference
This commit
- support array in component reference

chore: support array in component reference

---

pkg/service/service.go

Because
- we should allow base64 string with data MIME prefix
This commit
- allow base64 string with MIME prefix

chore: allow base64 string with MIME prefix

---

pkg/service/openapi.go
pkg/service/service.go
pkg/utils/utils.go
pkg/worker/workflow.go

Because
- sometimes, we may want to reference a "input" value from component
This commit
- allow reference from component input

chore: allow reference from component input

---

.github/workflows/integration-test.yml
Makefile
integration-test/const.js

Because
- we consolidated three gateways into one.
This commit
- update integration test to support consolidated gateway

chore: update integration test to support consolidated gateway

---

integration-test/const.js
integration-test/grpc-pipeline-private.js
integration-test/grpc-pipeline-public-with-jwt.js
integration-test/grpc-pipeline-public.js
integration-test/grpc-trigger-async.js
integration-test/grpc-trigger.js
integration-test/grpc.js
integration-test/rest-pipeline-private.js
integration-test/rest-pipeline-public-with-jwt.js
integration-test/rest-pipeline-public.js
integration-test/rest-trigger-async.js
integration-test/rest-trigger.js
integration-test/rest.js

Because
- we are going to support authentication in Instill-Core
This commit
- add authentication in integration tests

test(integration): add authentication in integration tests

---

pkg/service/convert.go

Because
- we should be able to know the component type when the `definition_name` is set
- the OpenAPI schema in pipeline release payload is missing
This commit
- fix the component type is unspecified when resource_name in not set
- fix the missing OpenAPI schema in pipeline release

fix(service): fix the component type is unspecified when `resource_name` in not set

---

config/config.yaml
go.mod
go.sum
pkg/datamodel/datamodel.go
pkg/db/migration/000006_init.up.sql
pkg/handler/publicHandler.go
pkg/service/convert.go
pkg/service/service.go

Because
- we want to store layout of pipeline builder in backend.
This commit
- add `metadata` column in pipeline and pipeline_release table
- add `metadata` field in pipeline and pipeline_release payload

feat(repository): add metadata field for pipeline

---

go.mod
go.sum
integration-test/const.js
pkg/service/openapi.go
pkg/service/service.go
pkg/worker/workflow.go

Because
- the wrong task might cause 500 error
This commit
- fix task bug
- adopt latest changes of connector-backend

fix(component): fix task bug

---

cmd/migration/000006_migrate.go
cmd/migration/main.go

Because
- we need to migrate the task of component
This commit
- add migration script for component task

chore(migration): update migration script

---

go.mod
pkg/service/convert.go

Because
- list pipelines when `view=VIEW_BASIC` should return null recipe
This commit
- fix the condition bug

fix(service): fix basic view should return null recipe

---

go.mod
go.sum
pkg/service/openapi.go

Because
- we introduced a new field `instillAcceptFormats` for smart-hint feature.
This commit
- update component pkg for instillAcceptFormats
- refactor corresponding codes for instillAcceptFormats

chore(deps): update component pkg for instillAcceptFormats

---

cmd/migration/000007_migrate.go
cmd/migration/main.go
config/config.yaml
go.mod
go.sum
pkg/service/service.go

Because
- the start operator configuration format has been changed
This commit
- add migration script for start operator

chore(migration): add migration script for start operator

---

pkg/service/openapi.go

Because
- a null check bug in OpenAPI generator
This commit
- fix OpenAPI generator bug

chore(service): fix OpenAPI generator bug

---

go.mod
go.sum
pkg/handler/connector.go
pkg/handler/pipeline.go
pkg/service/convert.go
pkg/service/service.go
pkg/usage/usage.go

Because
- we need to embed more data in response payload to reduce the API round trips
This commit
- embed owner data in pipeline, connector payload
- embed releases data in pipeline payload

chore(service): embed owner and releases data in pipeline, connector payload

---

go.mod
go.sum
pkg/service/service.go
pkg/service/validator.go
pkg/utils/dag.go
pkg/utils/utils.go
pkg/worker/workflow.go

Because
- we need to support conditional component so that the user can have more control for the pipeline
This commit
- implement conditional component. Only when the condition is `true`, the component can be excuted.

feat(service): implement conditional component

---

pkg/handler/pipeline.go
pkg/service/service.go
pkg/worker/workflow.go

Because
- we need to check subscription quota before triggering the pipeline
This commit
- check subscription quota
- fix influx db duplicated datapoints

chore(service): check subscription quota

---

pkg/service/service.go

Because
- when updating pipeline, we didn't correctly check the private pipeline quota
This commit
- fix bug on checking private pipeline quota when updating pipeline

chore(service): fix bug on checking private pipeline quota when updating pipeline

---

pkg/utils/dag.go
pkg/worker/workflow.go

Because
- conditional component should be abled to use component status as condition
This commit
- fix conditional component can't use component status

chore(worker): fix conditional component can't use component status

---

pkg/utils/dag.go
pkg/worker/workflow.go

Because
- We allow the component name to have a `-` character, but our condition field didn't work with this name.
This commit
- Fixes the condition field not working when the component name has `-`.

fix: fix condition field not working when component name has `-`

---

go.mod
go.sum

Accepts mp4 videos on Archetype AI upload task.
Because
- (write the reason why we need to consider this PR in a list)
This commit
- (write the summary of all commits in this PR in a list)

chore: update connector version

---

go.mod
go.sum
pkg/worker/workflow.go

Because
- The Numbers connector has been updated.
This commit
- Update connector package
- Remove unnecessary `custom` object in Numbers component config

chore(deps): update connector package for simplify Numbers connector process

---

go.mod
go.sum
pkg/handler/handler.go

Because
- We want to provide an endpoint to let Console check the availability of pipeline or connector name.
This commit
- Add `CheckName` endpoint

feat: add `CheckName` endpoint

---

LICENSE
pkg/acl/acl.go
pkg/handler/handler.go
pkg/service/service.go

Because
- conduct regular housecleaning
This commit
- update License
- lint code format

chore(repo): houseclean

---

pkg/utils/dag.go

Because
- We allow a hyphen in the component ID, but the `jsonpath` library we used does not allow variable names with a hyphen.
This commit
- Implements a workaround method to transcode the component ID into a valid variable name for `jsonpath`.

fix: fix component ID with a hyphen cannot be referenced

---

pkg/service/convert.go

Because
- To minimize API round trips between frontend and backend, we aim to return the corresponding connector/operator definition and connector data within the iterator.components.
This commit
- Embeds the definition and connector data in the iterator.components.

chore: include embedded definition and connector data in the iterator.components

---

cmd/migration/000012_migrate.go
cmd/migration/main.go
go.sum

Because
- The recipe format has been revamped.
This commit
- Adds migration script for new recipe format.

feat: add migration script for new recipe format

---

integration-test/proto/vdp/pipeline/v1beta/common.proto
integration-test/proto/vdp/pipeline/v1beta/component_definition.proto
integration-test/proto/vdp/pipeline/v1beta/connector.proto
integration-test/proto/vdp/pipeline/v1beta/pipeline.proto
integration-test/proto/vdp/pipeline/v1beta/pipeline_private_service.proto
integration-test/proto/vdp/pipeline/v1beta/pipeline_public_service.proto
pkg/middleware/interceptor.go
pkg/service/convert.go
pkg/service/errors.go

Because
- There are many potential bugs in the connector existence check when creating or updating a pipeline.
This commit
- Optimizes the connector existence check when creating or updating a pipeline.

chore: optimize connector existence check when creating or updating a pipeline

---

pkg/worker/dag.go
pkg/worker/workflow.go

Because
- The component condition evaluation has bugs due to the new refactoring.
This commit
- Fixes bugs in the condition field.

fix: fix condition field bugs

---

go.mod
go.sum
pkg/service/convert.go

Because
- `checkCredential()` will fail when when using an iterator.
This commit
- Fixes `checkCredential()`.

chore: fix `checkCredential()` failed when using an iterator

---

pkg/service/pipeline.go

Because
- In the CE version, we don't need to implement subscription related logic.
This commit
- Removes subscription related logic.

feat: remove subscription related logic

---

config/config.yaml
go.mod
go.sum
pkg/datamodel/datamodel.go
pkg/db/migration/000014_init.down.sql
pkg/db/migration/000014_init.up.sql
pkg/handler/pipeline.go
pkg/repository/repository.go
pkg/repository/transpiler.go
pkg/service/convert.go

Because
- We are going to introduce pipeline tag system. In the first step, we'll support `featured` tag only
This commit
- Creates tag table & related CRUD functions.
- Implements tag filter for pipeline.

feat: implement tag system for pipeline

---

pkg/recipe/dag.go
pkg/worker/workflow.go

Because
- The original condition field does not work.
This commit
- Fixes the condition field rendering bug.

fix: resolve condition field bug

---

Dockerfile
Dockerfile.dev

Because
- we want to use python lib in pdf component
This commit
- add python virtual machine in container

feat: support python code in components

---

cmd/migration/main.go
go.mod
go.sum
pkg/db/migration/convert/convert000015/main.go

Because
- We need to migrate the old recipe format to new one.
This commit
- Adds pipeline migration script.

chore: add pipeline migration script

---

pkg/worker/workflow.go

Because
- Error messages on insufficient credit aren't user-fiendly.
This commit
- Removes message extraction from activity error - the type is lost on the wire. Instead, we pass the temporal error generated in the activity, which contains the message.
- Improves activity errors for check / collect activities.

fix: improve pipeline usage error messages

---

pkg/service/pipeline.go
pkg/worker/workflow.go

Because
- By wrapping the temporal application error that comes from `ComponentActivity`, the `service` package failed to extract the error message.
This commit
- Delegate error wrapping to the temporal activities, return activity errors without wrapping.
- In addition to fixing the issue, the error message flow is improved by leveraging the temporal application's `Message` field instead of having an equivalent field within `Details`.

fix: return end-user error on component execution failure

---

cmd/migration/main.go
config/config.yaml
go.mod
go.sum
pkg/db/migration/000019.go
pkg/db/migration/convert/convert000013/main.go
pkg/db/migration/convert/convert000015/main.go
pkg/db/migration/convert/convert000016/main.go
pkg/db/migration/convert/convert000019/convert.go
pkg/db/migration/migration.go

Because
- Migration to `kebab-case` didn't include JQ task in JSON operator.
This commit
- Updates `component` to reference https://github.com/instill-ai/component/pull/219
- Adds a migration to update existing pipelines with `jq` tasks.

chore: use kebab-case in JSON operator input

---

go.mod
go.sum
pkg/db/migration/000020_init.down.sql
pkg/db/migration/000020_init.up.sql
pkg/db/migration/convert/convert000020/convert.go

Because
- We need to verify the existence of the Postgres extension before creating it.
This commit
- Fixes the migration script.

chore: fix migration script

---

pkg/db/migration/convert/convert000021/convert.go

Because
- We didn't migrate the document operator to reflect the field name change.
This commit
- Fixes the migration for the document operator.

chore: fix migration for document operator

---

pkg/service/pipeline.go

Because
- The run-on-schedule pipeline will also rely on the namespace secrets.
This commit
- Loads secrets when using run-on-schedule

chore: load secrets when using run-on-schedule

---

cmd/worker/main.go
pkg/service/pipeline.go
pkg/worker/main.go
pkg/worker/workflow.go

Because
- The pipeline shouldn't be loaded during schedule setup.
This commit
- Refactors the run-on-schedule workflow to load the pipeline during the pipeline run.

refactor: refactor run-on-schedule workflow

---

pkg/constant/constant.go
pkg/handler/formdata_handler.go

Because
- The form-data handler didn't work correctly.
This commit
- Fixes form-data handler.
- Increases the max payload size limit.

fix: fix form-data handler

---

config/config.go
config/config.yaml
pkg/recipe/variable.go

Because
- we want to add artifact component
This commit
- add setting for artifact-backend

chore(artifact): update artifact setting for artifact component

---

config/config.yaml
pkg/db/migration/convert/convert000022/convert.go
pkg/db/migration/migration.go

Because
- we change website to web and move to operator
This commit
- update data

chore(web): update data for component definition, pipeline, pipeline-release

---

.gitignore
config/config.go
config/config.yaml
go.mod
go.sum
pkg/minio/minio.go
pkg/service/pipeline.go

Because
- backend needs to store trigger input & output & files
This commit
- added minio connection

feat(minio): added minio connection

---

config/config.yaml
go.mod
go.sum
pkg/db/migration/convert/convert000024/convert.go
pkg/db/migration/migration.go

Because
- we update the document operator field
This commit
- migrate the field name

chore(document): update the key

---

pkg/repository/repository.go
pkg/service/convert.go
pkg/worker/workflow.go

Because
- recipe and input uploading randomly fail
This commit
- try to remove workflow.Go and so far it looks good

fix(run): fix the issue that sometimes recipe and input uploading fail in temporal with no error message

---

pkg/service/convert.go
pkg/service/pipeline.go
pkg/utils/utils.go

Because
- We'd like to simplify Instill Format 
This commit
- Supports new Instill Format in variable section

feat: support new Instill Format in variable section

---

pkg/worker/workflow.go

Because
- The memoryStore operation should be moved into Temporal Activity to avoid Temporal deadlock.
This commit
- Moves memoryStore operation into Temporal Activity

chore: move memoryStore operation into Temporal Activity

---

pkg/data/audio.go
pkg/data/video.go
pkg/service/pipeline.go

Because
- The Instill Format mapping was wrong.
This commit
- Fixes the bugs.

chore: fix Instill Format mapping

---

integration-test/pipeline/rest-integration.js
pkg/handler/integration.go
pkg/mock/repository_mock.gen.go
pkg/repository/repository.go
pkg/repository/repository_test.go
pkg/service/integration.go
pkg/service/main.go

Because
- Users need to modify and remove their collections
This commit
- Adds update & delete connection endpoints

feat(integration): add delete and update connection endpoints

---

cmd/init/presetdownloader/downloader.go
cmd/main/main.go
pkg/acl/acl.go
pkg/db/migration/convert/convert000016/main.go
pkg/external/external.go
pkg/handler/triggerhandler.go
pkg/logger/otel/const.go
pkg/middleware/middleware.go
pkg/recipe/dag.go
pkg/repository/repository.go
pkg/service/convert.go
pkg/service/pipeline.go

- Reduce memory duplicate (NewBuffer -> NewBufferString)
- Remove variable reassignment
- Add `TODO` comments for things should be take care

chore(all): improve code quality and readability lightly

---

pkg/worker/workflow.go

Because
- when a component run fails, the pipeline run logging state should be failed.
This commit
- capture component run error for run logging

feat(run): capture component run error for run logging

---

pkg/worker/workflow.go

Because
- The metric data point is written multiple times when the pipeline encounters an error.
This commit
- Fixes the issue of duplicated metric data points.

fix: fix duplicated metric datapoint

---

go.mod
go.sum

Because
- we fix bugs in component
This commit
- update dependency

chore(component): update dependency

---

pkg/service/pipeline.go
pkg/worker/workflow.go

Because
- The condition field can not reference variable.
This commit

fix: fix condition field can not reference variable

---

cmd/main/main.go
cmd/worker/main.go
go.mod
pkg/handler/main.go
pkg/memory/memory.go
pkg/service/pipeline.go
pkg/worker/main.go
pkg/worker/workflow.go

Because
- The scaling and graceful shutdown mechanism was not robust.
This commit
- Optimizes pipeline scaling and graceful shutdown mechanism.
- Remove the Temporal session and use a unique task queue for each worker.

refactor: optimize scaling and graceful shutdown mechanism

---

config/config.go
config/config.yaml
pkg/recipe/variable.go

Because
- we will have app backend server
This commit
- set the app backend config

chore: set config for app backend

---

config/config.yaml
go.mod
go.sum
pkg/db/migration/convert/convert000029/convert.go
pkg/db/migration/migration.go

Because
- we change the type of artifact to instill-artifact
This commit
- update recipe

chore(component): update artifact to instill-artifact

---

go.mod
go.sum
pkg/data/document.go

Because
- we want to support more types to convert to images
This commit
- update dependency because of licence issue
- update the code for component dependency

fix(document): change code for component dependency

---

pkg/service/pipeline.go

Because
- The target namespace during pipeline cloning was incorrect.
- The YAML layout needed to be preserved when cloning the pipeline.
This commit

fix: fix the wrong target namespace when cloning pipeline

---

pkg/component/base/execution_wrapper.go

Because
- The component render error was not being returned.
This commit

fix: fix the component render error was not being returned

---

.pre-commit-config.yaml
pkg/component/operator/text/v0/markdown_document.go
pkg/component/operator/text/v0/markdown_splitter_test.go
pkg/component/operator/text/v0/testdata/list_position_test.md

Because
- the position of the chunk is not correct
This commit
- fix the bug about the position
- exclude the test data in precommit
- add the test code for position bug

fix(text): fix the bug about the list position

---

cmd/main/main.go
pkg/worker/workflow.go

Because
- We can separate the queues for regular component activities and MinIO activities to enable more flexible resource management.
This commit
- Adds a dedicated queue for MinIO activities.

refactor: add a dedicated queue for MinIO activities

---

config/config.yaml

chore: fix db version

---

pkg/db/migration/convert/convert000031/convert.go
pkg/db/migration/convert/convert000032/convert.go

This commit
- Fixes migration bugs

chore: fix migration bugs

---

pkg/component/operator/web/v0/README.mdx
pkg/component/operator/web/v0/config/tasks.json
pkg/component/operator/web/v0/crawl_website.go

Because
- miss to update in go struct
This commit
- update go struct json

fix(web): fix bug

---

pkg/component/store/store.go

Because
- we will release instill app
This commit
- init instill app

chore(component): init instill app

---

pkg/component/application/email/v0/.compogen/extra-intro.mdx
pkg/component/data/instillartifact/v0/.compogen/extra-intro.mdx
pkg/component/data/instillartifact/v0/README.mdx
pkg/component/data/instillartifact/v0/config/tasks.json

Because
- the doc is unclear
This commit
- update doc

chore(component): update doc

---

pkg/component/ai/anthropic/v0/.compogen/bottom.mdx
pkg/component/ai/anthropic/v0/README.mdx
pkg/component/ai/anthropic/v0/config/tasks.json
pkg/component/application/github/v0/.compogen/bottom.mdx
pkg/component/application/github/v0/README.mdx

Because
- Anthropic released a new version of Sonnet model.
This commit
- Supports new Sonnet model

chore(anthropic): support new Sonnet model

---

pkg/data/document_test.go
pkg/data/image_test.go
pkg/data/video_test.go

Because
- The file URL in test cases used a link to the feature branch
This commit
- fixes the link

chore: fix file url in test-cases

---

cmd/main/main.go
config/config.go
go.mod
go.sum
pkg/service/main.go
pkg/service/metadataretention.go
pkg/service/pipeline.go
pkg/service/pipeline_test.go
pkg/worker/minioactivity.go
pkg/worker/workflow.go

Because
- expiry tag should be set by different environments
This commit
- add metadata retention handler

fix(run): add metadata retention handler

---

pkg/data/struct.go
pkg/worker/workflow.go

Because
- Previously, we did not support a `condition` field for the iterator.
This commit:
- Adds `condition` field support for the iterator.

feat: add `condition` field support for iterator

---

pkg/component/operator/audio/v0/config/definition.json
pkg/component/operator/document/v0/README.mdx
pkg/component/operator/document/v0/config/tasks.json
pkg/component/operator/document/v0/convert_document_to_markdown.go
pkg/component/operator/document/v0/convert_to_images.go
pkg/component/operator/document/v0/io.go
pkg/component/operator/document/v0/transformer/execution/task_convert_to_images.py
pkg/component/operator/document/v0/transformer/execution/task_convert_to_markdown.py
pkg/component/operator/document/v0/transformer/images.go
pkg/component/operator/document/v0/transformer/markdown.go
pkg/component/operator/document/v0/transformer/markdowntransformer.go
pkg/component/operator/document/v0/transformer/pdf_to_markdown/page_image_processor.py
pkg/component/operator/document/v0/transformer/pdf_to_markdown/pdf_transformer.py
pkg/component/operator/document/v0/transformer/pdftomarkdown.go

Because
- the users want to adjust the image resolution
This commit
- refactor the PDF to markdown transformer for better extensibility
- add resolution field
Note
- Test thread is in ins-6672 ✅ QAed thread

feat: add resolution field

---

pkg/data/array.go

Because
- We want to provide a simple syntax for users to get the length of an array.
This commit:
- Adds support for `length` attribute on array data

feat: support `length` attribute for array data

---

.github/workflows/integration-test.yml
Dockerfile.dev
pkg/data/array.go
pkg/data/format/format.go
pkg/data/format/value.go
pkg/data/map.go
pkg/data/null.go
pkg/data/struct.go
pkg/recipe/dag.go

Because
- we previously lacked stringify support for Map and Array data.
This commit
- adds stringify support for Map and Array data.

chore: add stringify support for Map and Array data

---

pkg/component/operator/text/v0/chunk_text.go
pkg/component/operator/text/v0/chunk_text_test.go
pkg/component/operator/text/v0/helper.go
pkg/component/operator/text/v0/markdown_document.go
pkg/component/operator/text/v0/markdown_splitter.go
pkg/component/operator/text/v0/markdown_splitter_test.go

Because
- the chunks are too small
This commit
- merge chunks
- update the markdown list & table definition

feat: improve markdown chunking

---

pkg/service/pipelinerun_test.go

Because
- unit tests are failing
This commit
- fix tests and add new ones

fix: unit tests

---

integration-test/pipeline/const.js
integration-test/pipeline/grpc-pipeline-private.js
integration-test/pipeline/grpc-pipeline-public-with-jwt.js
integration-test/pipeline/grpc-pipeline-public.js
integration-test/pipeline/grpc-trigger-async.js
integration-test/pipeline/grpc-trigger.js
integration-test/pipeline/rest-pipeline-private.js
integration-test/pipeline/rest-pipeline-public-with-jwt.js
integration-test/pipeline/rest-pipeline-public.js
integration-test/pipeline/rest-trigger-async.js
integration-test/pipeline/rest-trigger.js

This commit
- uses YAML recipe instead of JSON recipe in test cases

chore(test): use YAML recipe instead of JSON recipe in test cases

---

cmd/main/main.go
config/config.go
config/config.yaml
go.mod
go.sum
pkg/component/store/store.go
pkg/data/client/client.go
pkg/data/file.go
pkg/external/external.go
pkg/recipe/variable.go
pkg/repository/client.go
pkg/resource/resource.go
pkg/service/main.go
pkg/service/pipeline.go
pkg/service/pipeline_test.go
pkg/utils/utils.go
pkg/worker/main.go
pkg/worker/utils.go
pkg/worker/workflow.go

Because
- we want to read data directly from minio
- we want to upload output data to minio directly and return download url
This commit
- upload output data to minio
- read data from minio
- inject artifact clients to service and worker for the future usage
Note
- We will need to add test code for temporal worker

feat(vdp): integrate blob storage to vdp

---

go.mod
go.sum
pkg/worker/workflow.go

Because
- we want to align logger
This commit
- inject logger in common package

chore(pipeline): inject logger to x pkg

---

pkg/component/application/github/v0/config/events.json
pkg/component/application/github/v0/event_star_created.go
pkg/component/application/github/v0/event_structs.go
pkg/component/application/github/v0/event_utils.go
pkg/component/application/github/v0/main.go

This commit
- Uses kebab-case for event message format

chore(component,github): use kebab-case for event message format

---

pkg/service/pipeline.go

Because
- We cannot clone pipeline when there are connections in the `on` section of the recipe.
This commit
- fixes pipeline cloning issue with connections in the `on` section of the recipe.

chore(service): fix pipeline cloning issue with connections in the recipe `on` section

---

pkg/service/convert.go

Because
- item does not contain instill format
This commit
- insert instill format into items

fix(vdp): item does not contain the instill format, so we insert it

---

pkg/component/operator/document/v0/README.mdx
pkg/component/operator/document/v0/config/tasks.json
pkg/component/operator/document/v0/transformer/execution/task_convert_to_images.py
pkg/component/operator/document/v0/transformer/execution/task_convert_to_markdown.py

Because
- resolution 300 is optimal in most case
This commit
- change default resolution

chore(component): change default resolution from 500 to 300

---

pkg/component/ai/openai/v0/main.go
pkg/component/ai/openai/v0/textgeneration.go

Because
- OpenAI add support for streaming on the o1 models
This commit
-  supports streaming for o1-mini and o1-preview models

feat(component,openai): support streaming for o1-mini and o1-preview models

---

pkg/component/data/googlesheets/v0/config/tasks.json
pkg/component/data/googlesheets/v0/io.go
pkg/component/data/googlesheets/v0/task_list_rows.go
pkg/component/data/googlesheets/v0/task_list_rows_test.go

Because
- users might not not the size of the sheet.
This commit
- makes the row parameters in TASK_LIST_ROWS be optional

chore(component,googlesheets): make the row parameters in TASK_LIST_ROWS optional

---

go.mod
go.sum
integration-test/proto/vdp/pipeline/v1beta/integration.proto
integration-test/proto/vdp/pipeline/v1beta/pipeline_private_service.proto
integration-test/proto/vdp/pipeline/v1beta/pipeline_public_service.proto

This commit
- updates to the latest protogen-go package and proto files

chore(mod): update to the latest protogen-go package and proto files

---

pkg/component/operator/text/v0/helper.go
pkg/component/operator/text/v0/markdown_document.go
pkg/component/operator/text/v0/markdown_splitter.go
pkg/component/operator/text/v0/markdown_splitter_test.go

Because
- there is edge case influencing the use case
This commit
- improve overlap logic
- tune the list judgement logic

feat(text): improve markdown chunking

---

pkg/component/operator/web/v0/scrape_webpages.go

Because
- we want to keep the url and result in the same order
This commit
- add index in the channel struct to make sure the order correct

fix(web): fix url and markdown position

---

pkg/component/application/smartlead/v0/README.mdx
pkg/component/application/smartlead/v0/config/definition.json

Because
- there is typo
This commit
- fix typo

chore(smartlead): update doc

---

pkg/component/generic/schedule/v0/assets/schedule.svg

This commit
- add icon for `schedule` component

chore(component,schedule): add icon

---

pkg/component/application/smartlead/v0/config/tasks.json

Because
- we should use `instillShortDescription` as the task description
This commit
- fixes task descriptions

chore(component,smartlead): fix task descriptions

---

pkg/component/application/smartlead/v0/README.mdx
pkg/component/tools/compogen/cmd/testdata/readme-component1.txt
pkg/component/tools/compogen/pkg/gen/readme.go

Because
- {{}} will break the instill.tech
This commit
- fix compogen

feat(compogen): add {{}} case for compogen

---

pkg/component/generic/collection/v0/README.mdx
pkg/component/tools/compogen/cmd/testdata/readme-component1.txt
pkg/component/tools/compogen/pkg/gen/readme.go

Because
- `*` is not clear for users
This commit
- change `*` to `any`

feat(compogen): replace * to any

---

config/config.go

This commit
- fixes edition tag

chore(config): fix edition tag

---

pkg/component/data/googlesheets/v0/config/setup.json

This commit
- adjusts OAuth scope

chore(component,google-sheets): adjust OAuth scope

---

pkg/repository/repository.go

This commit
- enables `google-sheets` component

chore(component,google-sheets): enable `google-sheets` component

---

pkg/component/application/github/v0/client.go
pkg/component/application/github/v0/commits.go
pkg/component/application/github/v0/io.go
pkg/component/application/github/v0/issues.go
pkg/component/application/github/v0/mock_issue_service.go
pkg/component/application/github/v0/pull_request.go
pkg/component/application/github/v0/review_comment.go
pkg/component/application/github/v0/task_create_review_comment.go
pkg/component/application/github/v0/task_create_review_comment_test.go
pkg/component/application/github/v0/task_list_issues.go
pkg/component/application/github/v0/task_list_review_comments.go
pkg/component/application/github/v0/user.go
pkg/component/application/github/v0/utils.go
pkg/component/application/github/v0/webhook.go

Because
- The data structs in io.go were not correctly configured.
This commit
- Fixes the data structs.

fix(component,github): fix data structs

---

config/config.go
config/config.yaml
pkg/recipe/variable.go

Because
- [INS-7268](https://linear.app/instill-ai/issue/INS-7268/change-the-repo-name-app-backend-to-agent-backend)
This commit
- Implements the above

chore(github): rename app-backend to agent-backend

---

cmd/init/presetdownloader/downloader.go

Because:
- vdp-pipeline renaming caused the preset pipeline downloader to fail.
This commit:
- Fixes the preset pipeline downloader issue by using HTTP endpoints instead of gRPC endpoints.
Note:
- This fix is only a temporary solution. We should switch back to gRPC in the future.

chore(cmd): fix preset downloader error

---

config/config.yaml
integration-test/pipeline/const.js
integration-test/pipeline/rest-integration.js
integration-test/pipeline/rest-trigger.js
pkg/component/CONTRIBUTING.md
pkg/component/operator/document/v0/.compogen/bottom.mdx
pkg/component/operator/document/v0/README.mdx
pkg/component/operator/json/v0/.compogen/bottom.mdx
pkg/component/operator/json/v0/README.mdx
pkg/datamodel/datamodel.go
pkg/db/migration/convert/convert000040/convert.go
pkg/db/migration/migration.go
pkg/service/pipeline.go
pkg/service/utils.go

Because
- We are going to rename Instill Format to Instill Type.
This commit
- Renames `format` to `type` in variable section.

feat(recipe): rename `format` to `type` in variable section

---

pkg/component/ai/openai/v0/main.go

Because
- We used to check the parameters for different models, but it’s hard to maintain and can easily become outdated.
This commit
- Removes the response format check and relies on the vendor API to validate it.

fix(component,openai): remove response format check

---

pkg/external/external.go

Because
- we introduced a new blob-url path in this pattern `scheme://host/v1alpha/blob-urls/base64_encoded_presigned_url`
This commit
- supports new blob-url path in artifactBinaryFetcher

feat(external): support new blob-url path in artifactBinaryFetcher

---

.github/workflows/sync-component-docs-reusable.yml

Because
- when a component is removed, its component doc should be removed too
This commit
- implements the logic

ci(workflows): add component docs sync cleanup

---

.github/workflows/images.yml
.github/workflows/integration-test.yml

This commit
- adopts latest Makefile command in integration test

ci(test): adopts latest Makefile command in integration test

---

cmd/main/main.go
config/config.go
config/config.yaml

This commit
- aligns pipeline configuration with the other backends.

chore(otel,config): fix missing settings and configs

---

config/config.yaml
pkg/component/ai/perplexity/v0/README.mdx
pkg/component/ai/perplexity/v0/config/tasks.yaml
pkg/component/ai/perplexity/v0/io.go
pkg/component/ai/perplexity/v0/task_chat.go

This commit
- adopts latest perplexity API

feat(component,perplexity): adopt latest perplexity API

---

pkg/component/data/googlesheets/v0/task_insert_multiple_rows.go
pkg/component/data/googlesheets/v0/task_update_multiple_rows.go

Because
- The cell positions were wrong when inserting/updating rows
This commit
- fixes the wrong cell positions

fix(component,googlesheets): fix the wrong cell positions

---

config/config.yaml
pkg/external/external.go

This commit
- Updates the pipeline and blob buckets to the new names

feat(minio): use new bucket names

---

pkg/data/struct.go
pkg/data/struct_test.go

Because
- YAML multiline strings containing JSON schemas (like `response-schema: |`) could not be automatically converted to Go struct types like `genai.Schema`
This commit
- Adds automatic JSON string → struct conversion capability to the core unmarshaling framework
- Implements fast pre-check (`stringValue[0] == '{'` or `'['`) to avoid unnecessary JSON parsing overhead on regular strings
- Adds `tryUnmarshalJSONString()` helper function that uses direct `json.Unmarshal` to preserve complex nested structures

feat(data): enhance unmarshaler with JSON string to struct conversion

---

pkg/component/ai/gemini/v0/task_chat.go
pkg/component/ai/gemini/v0/task_chat_test.go

Because
- InlineData wasn't properly cleaned up in streaming mode, causing binary data exposure in JSON outputs
- Streaming responses didn't show images while non-streaming responses did, creating an inconsistent user experience
- Image extraction and InlineData cleanup logic was duplicated across different functions
This commit
- Creates a unified `processInlineDataInCandidates` function that handles both image extraction and InlineData cleanup with configurable behavior
- Fixes InlineData cleanup in streaming mode by ensuring binary data is removed from all intermediate responses
- Enables image extraction in streaming responses, making the behavior consistent with non-streaming mode
- Replaces duplicated cleanup logic in `renderFinal` and `buildStreamOutput` with the unified approach
- …

fix(component,ai,gemini): unify InlineData processing and enable images in streaming responses
